CREATE TABLE `ai_phone_calls` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`callSid` varchar(64),
	`callNumber` varchar(32),
	`callType` enum('vendor_complaint','shipping_inquiry','order_status','billing_dispute','return_request','account_inquiry','service_cancellation','delivery_reschedule','price_negotiation','general_inquiry','claims_filing','payment_followup','quote_request') NOT NULL,
	`direction` enum('outbound','inbound') NOT NULL DEFAULT 'outbound',
	`status` enum('queued','preparing','in_progress','on_hold','completed','failed','cancelled','requires_human') NOT NULL DEFAULT 'queued',
	`callPriority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
	`targetCompany` varchar(255) NOT NULL,
	`targetPhoneNumber` varchar(32),
	`targetDepartment` varchar(128),
	`subject` varchar(500) NOT NULL,
	`objective` text NOT NULL,
	`context` text,
	`relatedEntityType` varchar(50),
	`relatedEntityId` int,
	`vendorId` int,
	`customerId` int,
	`shipmentId` int,
	`orderId` int,
	`playbookId` varchar(64),
	`callScript` text,
	`requiredInfo` text,
	`fromPhoneNumber` varchar(32),
	`startedAt` timestamp,
	`endedAt` timestamp,
	`durationSeconds` int,
	`ivrPath` text,
	`menuSelections` text,
	`waitTimeSeconds` int,
	`aiConfidence` decimal(5,2),
	`objectiveCompleted` boolean DEFAULT false,
	`outcome` enum('resolved','partial_resolution','escalated_to_human','callback_scheduled','needs_followup','failed','voicemail_left'),
	`resolution` text,
	`referenceNumber` varchar(128),
	`callbackDate` timestamp,
	`followupActions` text,
	`quoteResults` text,
	`quotedTotalAmount` decimal(15,2),
	`quoteCurrency` varchar(3),
	`quoteValidUntil` timestamp,
	`quoteTerms` text,
	`recordingUrl` text,
	`transcriptUrl` text,
	`transcript` text,
	`transcriptSummary` text,
	`requiresApproval` boolean NOT NULL DEFAULT true,
	`approvedBy` int,
	`approvedAt` timestamp,
	`rejectedBy` int,
	`rejectedAt` timestamp,
	`rejectionReason` text,
	`callCost` decimal(8,4),
	`aiTokensUsed` int,
	`retryCount` int DEFAULT 0,
	`maxRetries` int DEFAULT 3,
	`lastError` text,
	`scheduledFor` timestamp,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_phone_calls_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_phone_call_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`phoneCallId` int NOT NULL,
	`eventType` enum('call_queued','call_preparing','call_started','ivr_navigation','agent_connected','ai_speaking','ai_listening','info_gathered','on_hold','transferred','objective_progress','call_ended','transcript_ready','error','human_takeover') NOT NULL,
	`logStatus` enum('info','success','warning','error') NOT NULL DEFAULT 'info',
	`message` text NOT NULL,
	`details` text,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	`durationMs` int,
	`logAiConfidence` decimal(5,2),
	`tokensUsed` int,
	CONSTRAINT `ai_phone_call_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_phone_call_playbooks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`playbookKey` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`targetCompany` varchar(255) NOT NULL,
	`phoneNumber` varchar(32),
	`department` varchar(128),
	`operatingHours` varchar(255),
	`ivrInstructions` text,
	`openingScript` text,
	`objectivePrompts` text,
	`closingScript` text,
	`requiredAccountInfo` text,
	`typicalQuestions` text,
	`escalationTriggers` text,
	`maxCallDuration` int,
	`avgCallDuration` int,
	`successRate` decimal(5,2),
	`totalCalls` int DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_phone_call_playbooks_id` PRIMARY KEY(`id`)
);
