CREATE TABLE IF NOT EXISTS `workflowRuns` (
  `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `workflowId` int NOT NULL,
  `runNumber` varchar(64) NOT NULL,
  `status` enum('queued','running','awaiting_approval','approved','rejected','completed','failed','cancelled','timed_out') NOT NULL DEFAULT 'queued',
  `triggeredBy` enum('schedule','event','threshold','manual','dependency') NOT NULL,
  `triggerData` text,
  `triggeredByUserId` int,
  `startedAt` timestamp NULL,
  `completedAt` timestamp NULL,
  `durationMs` int,
  `totalSteps` int DEFAULT 0,
  `completedSteps` int DEFAULT 0,
  `currentStepName` varchar(255),
  `progressPercent` int DEFAULT 0,
  `inputData` text,
  `outputData` text,
  `errorMessage` text,
  `errorDetails` text,
  `itemsProcessed` int DEFAULT 0,
  `itemsSucceeded` int DEFAULT 0,
  `itemsFailed` int DEFAULT 0,
  `totalValue` decimal(14,2),
  `attemptNumber` int DEFAULT 1,
  `parentRunId` int,
  `approvalRequestedAt` timestamp NULL,
  `approvedBy` int,
  `approvedAt` timestamp NULL,
  `rejectedBy` int,
  `rejectedAt` timestamp NULL,
  `rejectionReason` text,
  `escalatedAt` timestamp NULL,
  `escalatedTo` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
