CREATE TABLE `rd_tax_credit_studies` (
  `id` int AUTO_INCREMENT NOT NULL,
  `companyId` int,
  `taxYear` int NOT NULL,
  `studyName` varchar(255) NOT NULL,
  `status` enum('draft','in_progress','under_review','filed','amended') NOT NULL DEFAULT 'draft',
  `calculationMethod` enum('regular','asc') NOT NULL DEFAULT 'asc',
  `totalWageQre` decimal(15,2) DEFAULT '0',
  `totalSupplyQre` decimal(15,2) DEFAULT '0',
  `totalContractQre` decimal(15,2) DEFAULT '0',
  `totalQre` decimal(15,2) DEFAULT '0',
  `baseAmount` decimal(15,2) DEFAULT '0',
  `fixedBasePercentage` decimal(10,6) DEFAULT '0',
  `priorYear1Qre` decimal(15,2) DEFAULT '0',
  `priorYear2Qre` decimal(15,2) DEFAULT '0',
  `priorYear3Qre` decimal(15,2) DEFAULT '0',
  `averagePriorQre` decimal(15,2) DEFAULT '0',
  `grossCredit` decimal(15,2) DEFAULT '0',
  `section280CReduction` decimal(15,2) DEFAULT '0',
  `netCredit` decimal(15,2) DEFAULT '0',
  `currentYearGrossReceipts` decimal(15,2) DEFAULT '0',
  `averageBasePeriodGrossReceipts` decimal(15,2) DEFAULT '0',
  `filingDate` timestamp,
  `formNumber` varchar(20) DEFAULT '6765',
  `notes` text,
  `createdBy` int,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `rd_tax_credit_studies_id` PRIMARY KEY(`id`)
);

CREATE TABLE `rd_projects` (
  `id` int AUTO_INCREMENT NOT NULL,
  `studyId` int NOT NULL,
  `projectName` varchar(255) NOT NULL,
  `description` text,
  `businessComponent` varchar(255),
  `technologicalInNature` boolean DEFAULT false,
  `technologicalNatureNotes` text,
  `eliminationOfUncertainty` boolean DEFAULT false,
  `eliminationOfUncertaintyNotes` text,
  `processOfExperimentation` boolean DEFAULT false,
  `processOfExperimentationNotes` text,
  `permittedPurpose` boolean DEFAULT false,
  `permittedPurposeNotes` text,
  `qualifies` boolean DEFAULT false,
  `totalProjectQre` decimal(15,2) DEFAULT '0',
  `startDate` timestamp,
  `endDate` timestamp,
  `status` enum('active','completed','excluded') NOT NULL DEFAULT 'active',
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `rd_projects_id` PRIMARY KEY(`id`)
);

CREATE TABLE `rd_expenses` (
  `id` int AUTO_INCREMENT NOT NULL,
  `projectId` int NOT NULL,
  `studyId` int NOT NULL,
  `category` enum('wages','supplies','contract_research','cloud_computing') NOT NULL,
  `description` varchar(500),
  `employeeId` int,
  `employeeName` varchar(255),
  `rdPercentage` decimal(5,2) DEFAULT '100',
  `grossAmount` decimal(15,2) NOT NULL,
  `qualifiedAmount` decimal(15,2) NOT NULL,
  `contractResearchRate` decimal(5,2) DEFAULT '65',
  `vendorId` int,
  `vendorName` varchar(255),
  `periodStart` timestamp,
  `periodEnd` timestamp,
  `notes` text,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `rd_expenses_id` PRIMARY KEY(`id`)
);
