-- Migration 0037: Backfill tables defined in drizzle/schema.ts that have
-- no matching CREATE TABLE in any earlier SQL migration. Idempotent
-- (`IF NOT EXISTS`) so it is safe to re-apply on databases that already
-- have these tables (e.g. ones bootstrapped via `pnpm run db:push`).
--
-- Extracted from `drizzle-kit generate` output for the current schema and
-- filtered to 94 tables. 94 CREATE statements emitted.
-- Foreign-key ALTERs are intentionally omitted: they aren't idempotent and
-- would fail on databases that were bootstrapped via `pnpm run db:push`.

CREATE TABLE IF NOT EXISTS `agent_call_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`contactType` varchar(32) NOT NULL,
	`contactId` int NOT NULL,
	`contactName` varchar(255) NOT NULL,
	`phoneNumber` varchar(32) NOT NULL,
	`direction` enum('inbound','outbound') NOT NULL DEFAULT 'outbound',
	`status` enum('initiated','ringing','in_progress','completed','failed','no_answer') NOT NULL DEFAULT 'initiated',
	`purpose` text,
	`twilioCallSid` varchar(64),
	`crmInteractionId` int,
	`duration` int,
	`recordingUrl` text,
	`transcript` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `agent_call_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `agent_run_steps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` int NOT NULL,
	`iteration` int NOT NULL,
	`toolName` varchar(128),
	`toolInput` text,
	`toolResult` text,
	`assistantMessage` text,
	`stopReason` varchar(64),
	`tokensUsed` int,
	`durationMs` int,
	`isError` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `agent_run_steps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `agent_runs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`companyId` int,
	`goal` text NOT NULL,
	`maxIterations` int NOT NULL DEFAULT 20,
	`context` text,
	`status` enum('running','completed','failed','max_iterations') NOT NULL DEFAULT 'running',
	`iterations` int NOT NULL DEFAULT 0,
	`summary` text,
	`errorMessage` text,
	`totalTokensUsed` int NOT NULL DEFAULT 0,
	`totalDurationMs` int,
	`toolCallCount` int NOT NULL DEFAULT 0,
	`messageHistory` text,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `agent_runs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `approvalThresholds` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`name` varchar(255) NOT NULL,
	`entityType` enum('purchase_order','work_order','inventory_transfer','freight_booking','payment','vendor_rfq','price_override','exception') NOT NULL,
	`autoApproveMaxAmount` decimal(14,2),
	`level1MaxAmount` decimal(14,2),
	`level2MaxAmount` decimal(14,2),
	`level3MaxAmount` decimal(14,2),
	`level1Roles` text,
	`level2Roles` text,
	`level3Roles` text,
	`execRoles` text,
	`level1EscalationMinutes` int DEFAULT 60,
	`level2EscalationMinutes` int DEFAULT 120,
	`level3EscalationMinutes` int DEFAULT 240,
	`conditions` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `approvalThresholds_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `autonomousDecisions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` int,
	`stepId` int,
	`decisionType` enum('vendor_selection','quantity_calculation','timing_decision','routing_decision','pricing_acceptance','exception_handling','priority_assignment','allocation_decision','forecast_adjustment','reorder_trigger','approval_routing') NOT NULL,
	`decisionContext` text,
	`optionsConsidered` text,
	`chosenOption` text,
	`aiReasoning` text,
	`confidence` decimal(5,2),
	`entityType` varchar(64),
	`entityId` int,
	`estimatedImpact` text,
	`actualImpact` text,
	`wasOverridden` boolean DEFAULT false,
	`overriddenBy` int,
	`overrideReason` text,
	`feedbackScore` int,
	`feedbackNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `autonomousDecisions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `bank_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`externalId` varchar(128),
	`accountName` varchar(256),
	`accountId` varchar(128),
	`date` timestamp NOT NULL,
	`amount` decimal(14,2) NOT NULL,
	`type` enum('debit','credit') NOT NULL,
	`description` varchar(512),
	`counterpartyName` varchar(256),
	`status` varchar(64),
	`category` varchar(128),
	`accountCode` varchar(32),
	`categorizationStatus` enum('uncategorized','ai_suggested','confirmed','manual') DEFAULT 'uncategorized',
	`aiConfidence` int,
	`matchedInvoiceId` int,
	`matchedPurchaseOrderId` int,
	`matchedVendorId` int,
	`matchedCustomerId` int,
	`syncedToQuickbooks` boolean DEFAULT false,
	`source` enum('mercury','quickbooks','manual') DEFAULT 'mercury',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bank_transactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `bank_transactions_externalId_unique` UNIQUE(`externalId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codeAiSessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`snippetId` int,
	`action` enum('generate','explain','debug','refactor','review','test','document','optimize') NOT NULL,
	`prompt` text NOT NULL,
	`inputCode` text,
	`outputCode` text,
	`explanation` text,
	`model` varchar(128),
	`tokensUsed` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `codeAiSessions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codeExecutions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`snippetId` int,
	`language` varchar(64) NOT NULL,
	`code` text NOT NULL,
	`output` text,
	`errorOutput` text,
	`exitCode` int,
	`executionTimeMs` int,
	`status` enum('pending','running','completed','failed','timeout') NOT NULL DEFAULT 'pending',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `codeExecutions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `codeSnippets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`language` varchar(64) NOT NULL DEFAULT 'typescript',
	`code` text NOT NULL,
	`tags` text,
	`isPublic` boolean NOT NULL DEFAULT false,
	`folderId` int,
	`version` int NOT NULL DEFAULT 1,
	`parentSnippetId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `codeSnippets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `cogsPeriodSummary` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`productId` int,
	`periodType` enum('daily','weekly','monthly','quarterly','yearly') NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalQuantitySold` decimal(15,4) NOT NULL,
	`totalCogs` decimal(15,2) NOT NULL,
	`totalRevenue` decimal(15,2),
	`averageUnitCogs` decimal(15,4),
	`grossMargin` decimal(15,2),
	`grossMarginPercent` decimal(8,4),
	`costingMethod` enum('fifo','lifo','weighted_average'),
	`beginningInventoryValue` decimal(15,2),
	`purchasesValue` decimal(15,2),
	`endingInventoryValue` decimal(15,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cogsPeriodSummary_id` PRIMARY KEY(`id`),
	CONSTRAINT `idx_cogs_period_unique` UNIQUE(`companyId`,`productId`,`periodType`,`periodStart`,`periodEnd`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `cogsRecords` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`productId` int NOT NULL,
	`warehouseId` int,
	`orderId` int,
	`salesOrderLineId` int,
	`costingMethod` enum('fifo','lifo','weighted_average') NOT NULL,
	`quantitySold` decimal(15,4) NOT NULL,
	`unitCogs` decimal(15,4) NOT NULL,
	`totalCogs` decimal(15,2) NOT NULL,
	`unitRevenue` decimal(15,2),
	`totalRevenue` decimal(15,2),
	`grossMargin` decimal(15,2),
	`grossMarginPercent` decimal(8,4),
	`currency` varchar(3) DEFAULT 'USD',
	`periodDate` timestamp NOT NULL,
	`layerBreakdown` text,
	`notes` text,
	`calculatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cogsRecords_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `cogsTransactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionNumber` varchar(64) NOT NULL,
	`salesOrderId` int NOT NULL,
	`salesOrderLineId` int NOT NULL,
	`productId` int NOT NULL,
	`lotId` int,
	`warehouseId` int,
	`quantitySold` decimal(15,4) NOT NULL,
	`unitCost` decimal(15,4) NOT NULL,
	`productCost` decimal(15,2) NOT NULL,
	`freightCostAllocated` decimal(15,2) DEFAULT '0',
	`customsCostAllocated` decimal(15,2) DEFAULT '0',
	`insuranceCostAllocated` decimal(15,2) DEFAULT '0',
	`otherCostAllocated` decimal(15,2) DEFAULT '0',
	`totalCOGS` decimal(15,2) NOT NULL,
	`revenueAmount` decimal(15,2) NOT NULL,
	`grossProfit` decimal(15,2) NOT NULL,
	`costingMethod` enum('fifo','lifo','average','specific') NOT NULL DEFAULT 'fifo',
	`notes` text,
	`transactionDate` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cogsTransactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `contact_captures` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactId` int,
	`captureMethod` enum('iphone_bump','airdrop','nfc','qr_code','whatsapp_scan','linkedin_scan','business_card_scan','manual') NOT NULL,
	`rawData` text NOT NULL,
	`parsedData` text,
	`vcardData` text,
	`linkedinProfileUrl` varchar(512),
	`linkedinProfileData` text,
	`imageUrl` text,
	`ocrText` text,
	`status` enum('pending','parsed','contact_created','merged','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`capturedAt` timestamp NOT NULL DEFAULT (now()),
	`capturedBy` int,
	`eventName` varchar(255),
	`eventLocation` varchar(255),
	`deviceType` varchar(64),
	`deviceId` varchar(128),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contact_captures_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `copacker_inventory_update_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`updateId` int NOT NULL,
	`productId` int NOT NULL,
	`previousQuantity` decimal(15,4),
	`newQuantity` decimal(15,4) NOT NULL,
	`quantityReceived` decimal(15,4) DEFAULT '0',
	`quantityShipped` decimal(15,4) DEFAULT '0',
	`quantityDamaged` decimal(15,4) DEFAULT '0',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `copacker_inventory_update_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `copacker_inventory_updates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`warehouseId` int NOT NULL,
	`submittedBy` int NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`status` enum('draft','submitted','reviewed','approved','rejected') NOT NULL DEFAULT 'draft',
	`notes` text,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `copacker_inventory_updates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `copacker_invoice_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoiceId` int NOT NULL,
	`description` text NOT NULL,
	`quantity` decimal(15,4) NOT NULL,
	`unitPrice` decimal(15,2) NOT NULL,
	`totalAmount` decimal(15,2) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `copacker_invoice_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `copacker_invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`warehouseId` int NOT NULL,
	`submittedBy` int NOT NULL,
	`invoiceNumber` varchar(64) NOT NULL,
	`invoiceDate` timestamp NOT NULL,
	`dueDate` timestamp,
	`description` text,
	`subtotal` decimal(15,2) NOT NULL,
	`taxAmount` decimal(15,2) DEFAULT '0',
	`totalAmount` decimal(15,2) NOT NULL,
	`currency` varchar(3) DEFAULT 'USD',
	`status` enum('draft','submitted','under_review','approved','rejected','paid') NOT NULL DEFAULT 'draft',
	`fileUrl` text,
	`fileKey` varchar(512),
	`fileName` varchar(255),
	`mimeType` varchar(128),
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`rejectionReason` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `copacker_invoices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `copacker_shipping_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`warehouseId` int NOT NULL,
	`shipmentId` int,
	`uploadedBy` int NOT NULL,
	`documentType` enum('bill_of_lading','packing_list','commercial_invoice','proof_of_delivery','weight_certificate','inspection_report','customs_declaration','other') NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`fileUrl` text NOT NULL,
	`fileKey` varchar(512) NOT NULL,
	`fileSize` int,
	`mimeType` varchar(128),
	`status` enum('uploaded','reviewed','approved','rejected') NOT NULL DEFAULT 'uploaded',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`rejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `copacker_shipping_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `crm_campaign_recipients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`contactId` int NOT NULL,
	`email` varchar(320) NOT NULL,
	`status` enum('pending','sent','delivered','opened','clicked','bounced','unsubscribed') DEFAULT 'pending',
	`sentAt` timestamp,
	`deliveredAt` timestamp,
	`openedAt` timestamp,
	`clickedAt` timestamp,
	`messageId` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `crm_campaign_recipients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `crm_contact_tags` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactId` int NOT NULL,
	`tagId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `crm_contact_tags_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `crm_contacts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`firstName` varchar(128) NOT NULL,
	`lastName` varchar(128),
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320),
	`phone` varchar(32),
	`whatsappNumber` varchar(32),
	`linkedinUrl` varchar(512),
	`organization` varchar(255),
	`jobTitle` varchar(255),
	`department` varchar(128),
	`address` text,
	`city` varchar(128),
	`state` varchar(64),
	`country` varchar(64),
	`postalCode` varchar(20),
	`contactType` enum('lead','prospect','customer','partner','investor','donor','vendor','other') NOT NULL DEFAULT 'lead',
	`source` enum('iphone_bump','whatsapp','linkedin_scan','business_card','website','referral','event','cold_outreach','import','manual','fireflies') NOT NULL DEFAULT 'manual',
	`status` enum('active','inactive','unsubscribed','bounced') NOT NULL DEFAULT 'active',
	`pipelineStage` enum('new','contacted','qualified','proposal','negotiation','won','lost') DEFAULT 'new',
	`dealValue` decimal(15,2),
	`dealCurrency` varchar(3) DEFAULT 'USD',
	`leadScore` int DEFAULT 0,
	`lastContactedAt` timestamp,
	`lastRepliedAt` timestamp,
	`nextFollowUpAt` timestamp,
	`totalInteractions` int DEFAULT 0,
	`preferredChannel` enum('email','whatsapp','phone','sms','linkedin') DEFAULT 'email',
	`optedOutEmail` boolean DEFAULT false,
	`optedOutSms` boolean DEFAULT false,
	`optedOutWhatsapp` boolean DEFAULT false,
	`customerId` int,
	`hubspotContactId` varchar(64),
	`salesforceContactId` varchar(64),
	`captureDeviceId` varchar(128),
	`captureSessionId` varchar(128),
	`capturedBy` int,
	`captureData` text,
	`notes` text,
	`tags` text,
	`customFields` text,
	`avatarUrl` text,
	`assignedTo` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crm_contacts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `crm_deals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pipelineId` int NOT NULL,
	`contactId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`stage` varchar(64) NOT NULL,
	`amount` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`probability` int DEFAULT 0,
	`expectedCloseDate` timestamp,
	`status` enum('open','won','lost','stalled') NOT NULL DEFAULT 'open',
	`lostReason` varchar(255),
	`wonAt` timestamp,
	`lostAt` timestamp,
	`assignedTo` int,
	`source` varchar(128),
	`campaign` varchar(128),
	`notes` text,
	`customFields` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crm_deals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `crm_email_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`subject` varchar(500) NOT NULL,
	`bodyHtml` text NOT NULL,
	`bodyText` text,
	`type` enum('newsletter','drip','announcement','follow_up','custom') DEFAULT 'custom',
	`status` enum('draft','scheduled','sending','sent','paused','cancelled') DEFAULT 'draft',
	`scheduledAt` timestamp,
	`sentAt` timestamp,
	`targetTags` text,
	`targetContactTypes` text,
	`targetPipelineStages` text,
	`totalRecipients` int DEFAULT 0,
	`sentCount` int DEFAULT 0,
	`deliveredCount` int DEFAULT 0,
	`openedCount` int DEFAULT 0,
	`clickedCount` int DEFAULT 0,
	`bouncedCount` int DEFAULT 0,
	`unsubscribedCount` int DEFAULT 0,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crm_email_campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `crm_interactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactId` int NOT NULL,
	`channel` enum('email','whatsapp','sms','phone','meeting','linkedin','note','task') NOT NULL,
	`interactionType` enum('sent','received','call_made','call_received','meeting_scheduled','meeting_completed','note_added','task_completed') NOT NULL,
	`subject` varchar(500),
	`content` text,
	`summary` text,
	`emailId` int,
	`whatsappMessageId` int,
	`callDuration` int,
	`callOutcome` enum('answered','voicemail','no_answer','busy','wrong_number'),
	`meetingStartTime` timestamp,
	`meetingEndTime` timestamp,
	`meetingLocation` varchar(255),
	`meetingLink` varchar(512),
	`opened` boolean DEFAULT false,
	`clicked` boolean DEFAULT false,
	`replied` boolean DEFAULT false,
	`sentiment` enum('positive','neutral','negative'),
	`aiNotes` text,
	`relatedDealId` int,
	`performedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crm_interactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `crm_pipelines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`type` enum('sales','fundraising','partnerships','other') NOT NULL DEFAULT 'sales',
	`stages` text NOT NULL,
	`isDefault` boolean DEFAULT false,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `crm_pipelines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `crm_tags` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(64) NOT NULL,
	`color` varchar(7) DEFAULT '#3B82F6',
	`category` enum('contact','deal','general') DEFAULT 'general',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `crm_tags_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `dataRoomChecklistItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`checklistId` int NOT NULL,
	`dataRoomId` int NOT NULL,
	`categoryName` varchar(255),
	`itemName` varchar(255) NOT NULL,
	`itemDescription` text,
	`requirement` enum('required','optional','conditional') NOT NULL DEFAULT 'required',
	`status` enum('missing','pending','uploaded','approved','rejected','waived','not_applicable','complete','partial') NOT NULL DEFAULT 'missing',
	`matchKeywords` text,
	`matchFileTypes` text,
	`linkedDocumentId` int,
	`linkedDocumentIds` text,
	`linkedDocumentCount` int DEFAULT 0,
	`sortOrder` int DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dataRoomChecklistItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `dataRoomChecklists` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`templateId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`status` enum('active','archived') NOT NULL DEFAULT 'active',
	`createdBy` int,
	`totalItems` int NOT NULL DEFAULT 0,
	`completedItems` int NOT NULL DEFAULT 0,
	`partialItems` int NOT NULL DEFAULT 0,
	`missingItems` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dataRoomChecklists_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `data_room_drive_sync_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`googleDriveFolderId` varchar(255) NOT NULL,
	`googleDriveFolderName` varchar(255),
	`googleDriveFolderUrl` varchar(512),
	`syncEnabled` boolean NOT NULL DEFAULT true,
	`syncFrequencyMinutes` int DEFAULT 60,
	`syncMode` enum('one_way_import','one_way_export','bidirectional') NOT NULL DEFAULT 'one_way_import',
	`syncSubfolders` boolean NOT NULL DEFAULT true,
	`includeFileTypes` text,
	`excludeFileTypes` text,
	`maxFileSizeMb` int DEFAULT 100,
	`folderMapping` text,
	`lastSyncAt` timestamp,
	`lastSyncStatus` enum('success','partial','failed','in_progress'),
	`lastSyncError` text,
	`lastSyncFilesAdded` int DEFAULT 0,
	`lastSyncFilesUpdated` int DEFAULT 0,
	`lastSyncFilesRemoved` int DEFAULT 0,
	`syncUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_room_drive_sync_config_id` PRIMARY KEY(`id`),
	CONSTRAINT `data_room_drive_sync_config_dataRoomId_unique` UNIQUE(`dataRoomId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `data_room_drive_sync_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`syncConfigId` int NOT NULL,
	`syncType` enum('manual','scheduled','webhook') NOT NULL,
	`status` enum('started','in_progress','completed','failed','cancelled') NOT NULL DEFAULT 'started',
	`filesScanned` int DEFAULT 0,
	`filesAdded` int DEFAULT 0,
	`filesUpdated` int DEFAULT 0,
	`filesRemoved` int DEFAULT 0,
	`filesSkipped` int DEFAULT 0,
	`foldersCreated` int DEFAULT 0,
	`errors` text,
	`warnings` text,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`durationMs` int,
	`triggeredBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `data_room_drive_sync_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `data_room_email_access_rules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`ruleType` enum('allow_email','allow_domain','block_email','block_domain') NOT NULL,
	`emailPattern` varchar(320) NOT NULL,
	`allowDownload` boolean DEFAULT true,
	`allowPrint` boolean DEFAULT true,
	`maxViews` int,
	`expiresAt` timestamp,
	`requireNdaSignature` boolean DEFAULT true,
	`autoApprove` boolean DEFAULT false,
	`notifyOnAccess` boolean DEFAULT true,
	`notifyEmail` varchar(320),
	`isActive` boolean NOT NULL DEFAULT true,
	`priority` int DEFAULT 0,
	`createdBy` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_room_email_access_rules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `data_room_visitor_sessions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int NOT NULL,
	`visitorId` int NOT NULL,
	`linkId` int,
	`sessionStartAt` timestamp NOT NULL DEFAULT (now()),
	`sessionEndAt` timestamp,
	`totalDurationMs` int DEFAULT 0,
	`activeDurationMs` int DEFAULT 0,
	`idleDurationMs` int DEFAULT 0,
	`documentsViewed` int DEFAULT 0,
	`pagesViewed` int DEFAULT 0,
	`totalScrollDistance` int DEFAULT 0,
	`totalClicks` int DEFAULT 0,
	`downloadsCount` int DEFAULT 0,
	`printsCount` int DEFAULT 0,
	`deviceType` varchar(32),
	`browser` varchar(64),
	`browserVersion` varchar(32),
	`os` varchar(64),
	`osVersion` varchar(32),
	`screenResolution` varchar(20),
	`ipAddress` varchar(45),
	`country` varchar(64),
	`region` varchar(64),
	`city` varchar(64),
	`timezone` varchar(64),
	`referrer` varchar(512),
	`utmSource` varchar(128),
	`utmMedium` varchar(128),
	`utmCampaign` varchar(128),
	`sessionToken` varchar(128),
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `data_room_visitor_sessions_id` PRIMARY KEY(`id`),
	CONSTRAINT `data_room_visitor_sessions_sessionToken_unique` UNIQUE(`sessionToken`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `document_page_views` (
	`id` int AUTO_INCREMENT NOT NULL,
	`documentId` int NOT NULL,
	`visitorId` int NOT NULL,
	`viewSessionId` int,
	`linkId` int,
	`pageNumber` int NOT NULL,
	`pageLabel` varchar(100),
	`enterTime` timestamp NOT NULL DEFAULT (now()),
	`exitTime` timestamp,
	`durationMs` int DEFAULT 0,
	`scrollDepth` int,
	`mouseMovements` int DEFAULT 0,
	`clicks` int DEFAULT 0,
	`zoomLevel` int DEFAULT 100,
	`deviceType` varchar(32),
	`screenWidth` int,
	`screenHeight` int,
	`viewportWidth` int,
	`viewportHeight` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `document_page_views_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `dueDiligenceCategories` (
	`id` int AUTO_INCREMENT NOT NULL,
	`templateId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dueDiligenceCategories_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `dueDiligenceItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`templateId` int NOT NULL,
	`categoryId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`required` boolean NOT NULL DEFAULT true,
	`requirement` enum('required','optional','conditional') NOT NULL DEFAULT 'required',
	`matchKeywords` text,
	`matchFileTypes` text,
	`sortOrder` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dueDiligenceItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `dueDiligenceTemplates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`type` enum('fundraising','ma','full','series_b') NOT NULL DEFAULT 'full',
	`isPublic` boolean NOT NULL DEFAULT false,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `dueDiligenceTemplates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_compliance_scorecards` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tradingPartnerId` int NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalTransactions` int DEFAULT 0,
	`successfulTransactions` int DEFAULT 0,
	`failedTransactions` int DEFAULT 0,
	`avgProcessingTimeSeconds` int,
	`onTimeAckPercentage` decimal(5,2),
	`onTimeShipPercentage` decimal(5,2),
	`fillRatePercentage` decimal(5,2),
	`asnAccuracyPercentage` decimal(5,2),
	`chargebackCount` int DEFAULT 0,
	`chargebackAmount` decimal(15,2) DEFAULT '0',
	`overallScore` decimal(5,2),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `edi_compliance_scorecards_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_control_numbers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tradingPartnerId` int NOT NULL,
	`controlNumberType` enum('isa','gs','st') NOT NULL,
	`lastUsedNumber` int NOT NULL DEFAULT 0,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `edi_control_numbers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_document_maps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tradingPartnerId` int NOT NULL,
	`transactionSetCode` varchar(10) NOT NULL,
	`direction` enum('inbound','outbound') NOT NULL,
	`version` varchar(20) NOT NULL DEFAULT '004010',
	`mappingRules` text NOT NULL,
	`validationRules` text,
	`transformTemplate` text,
	`isActive` boolean DEFAULT true,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `edi_document_maps_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_product_crosswalks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tradingPartnerId` int NOT NULL,
	`productId` int NOT NULL,
	`buyerPartNumber` varchar(64),
	`vendorPartNumber` varchar(64),
	`upc` varchar(14),
	`buyerDescription` varchar(255),
	`unitOfMeasure` varchar(10) DEFAULT 'EA',
	`packSize` int,
	`innerPackSize` int,
	`caseUpc` varchar(14),
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `edi_product_crosswalks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`isaId` varchar(15) NOT NULL,
	`isaQualifier` varchar(2) NOT NULL DEFAULT 'ZZ',
	`gsApplicationCode` varchar(15) NOT NULL,
	`companyName` varchar(255),
	`ackTimeoutMinutes` int DEFAULT 30,
	`autoSend997` boolean DEFAULT true,
	`defaultTestMode` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `edi_settings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_ship_to_locations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tradingPartnerId` int NOT NULL,
	`locationCode` varchar(32) NOT NULL,
	`locationType` enum('store','distribution_center','warehouse','cross_dock') NOT NULL DEFAULT 'store',
	`name` varchar(255) NOT NULL,
	`address` text,
	`city` varchar(128),
	`state` varchar(64),
	`postalCode` varchar(20),
	`country` varchar(64) DEFAULT 'US',
	`gln` varchar(13),
	`duns` varchar(9),
	`contactName` varchar(255),
	`contactPhone` varchar(32),
	`receivingHours` text,
	`specialInstructions` text,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `edi_ship_to_locations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_trading_partners` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`customerId` int,
	`name` varchar(255) NOT NULL,
	`partnerType` enum('retailer','distributor','wholesaler','marketplace','3pl') NOT NULL DEFAULT 'retailer',
	`isaId` varchar(15) NOT NULL,
	`isaQualifier` varchar(2) NOT NULL DEFAULT 'ZZ',
	`gsId` varchar(15) NOT NULL,
	`connectionType` enum('as2','sftp','van','api','email') NOT NULL DEFAULT 'sftp',
	`connectionHost` varchar(512),
	`connectionPort` int,
	`connectionUsername` varchar(255),
	`connectionPassword` text,
	`connectionCertificate` text,
	`as2Id` varchar(128),
	`as2Url` varchar(512),
	`supportedDocuments` text,
	`requiresFunctionalAck` boolean DEFAULT true,
	`ackTimeoutHours` int DEFAULT 24,
	`testMode` boolean DEFAULT true,
	`ediContactName` varchar(255),
	`ediContactEmail` varchar(320),
	`ediContactPhone` varchar(32),
	`status` enum('active','inactive','testing','onboarding') NOT NULL DEFAULT 'onboarding',
	`notes` text,
	`lastTransactionAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `edi_trading_partners_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_transaction_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionId` int NOT NULL,
	`lineNumber` int NOT NULL,
	`buyerPartNumber` varchar(64),
	`vendorPartNumber` varchar(64),
	`upc` varchar(14),
	`sku` varchar(64),
	`productId` int,
	`description` text,
	`quantity` decimal(15,4) NOT NULL,
	`unitOfMeasure` varchar(10) DEFAULT 'EA',
	`unitPrice` decimal(15,4),
	`totalAmount` decimal(15,2),
	`requestedShipDate` timestamp,
	`requestedDeliveryDate` timestamp,
	`shipToLocationCode` varchar(32),
	`shipToName` varchar(255),
	`allowanceChargeAmount` decimal(15,2),
	`allowanceChargeType` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `edi_transaction_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `edi_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tradingPartnerId` int NOT NULL,
	`transactionSetCode` varchar(10) NOT NULL,
	`direction` enum('inbound','outbound') NOT NULL,
	`interchangeControlNumber` varchar(9),
	`groupControlNumber` varchar(9),
	`transactionSetControlNumber` varchar(9),
	`rawContent` text,
	`parsedData` text,
	`orderId` int,
	`invoiceId` int,
	`shipmentId` int,
	`purchaseOrderNumber` varchar(64),
	`status` enum('received','parsing','parsed','validated','processing','processed','error','rejected','acknowledged') NOT NULL DEFAULT 'received',
	`errorMessage` text,
	`errorDetails` text,
	`ackRequired` boolean DEFAULT false,
	`ackStatus` enum('pending','sent','received','overdue'),
	`ackTransactionId` int,
	`ackSentAt` timestamp,
	`ackReceivedAt` timestamp,
	`processedAt` timestamp,
	`processedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `edi_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `email_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`emailMessageId` int,
	`providerMessageId` varchar(255),
	`providerEventType` varchar(64) NOT NULL,
	`providerTimestamp` timestamp,
	`email` varchar(320),
	`rawEventJson` json,
	`reason` text,
	`bounceType` varchar(64),
	`processedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `email_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `email_messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`toEmail` varchar(320) NOT NULL,
	`toName` varchar(255),
	`fromEmail` varchar(320),
	`fromName` varchar(255),
	`replyTo` varchar(320),
	`subject` varchar(512) NOT NULL,
	`templateName` enum('QUOTE','PO','SHIPMENT','ALERT','RFQ','INVOICE','PAYMENT_REMINDER','WELCOME','GENERAL'),
	`payloadJson` json,
	`idempotencyKey` varchar(255),
	`status` enum('queued','sending','sent','failed','bounced','delivered','opened','clicked') NOT NULL DEFAULT 'queued',
	`providerMessageId` varchar(255),
	`retryCount` int DEFAULT 0,
	`maxRetries` int DEFAULT 3,
	`nextRetryAt` timestamp,
	`errorJson` json,
	`relatedEntityType` varchar(64),
	`relatedEntityId` int,
	`triggeredBy` int,
	`aiGenerated` boolean DEFAULT false,
	`scheduledAt` timestamp,
	`sentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `email_messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `equity_grants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`stakeholderId` int NOT NULL,
	`shareClassId` int NOT NULL,
	`grantType` enum('purchase','option_iso','option_nso','rsu','restricted_stock','convertible_note','safe','warrant','secondary') NOT NULL,
	`grantDate` timestamp NOT NULL,
	`shares` decimal(18,4) NOT NULL,
	`pricePerShare` decimal(18,4) NOT NULL,
	`totalValue` decimal(18,2),
	`status` enum('active','partially_vested','fully_vested','exercised','cancelled','expired','converted') DEFAULT 'active',
	`vestingStartDate` timestamp,
	`vestingEndDate` timestamp,
	`vestingSchedule` enum('none','monthly','quarterly','annually','custom') DEFAULT 'none',
	`cliffMonths` int DEFAULT 0,
	`totalVestingMonths` int DEFAULT 0,
	`accelerationOnChange` boolean DEFAULT false,
	`doubleAcceleration` boolean DEFAULT false,
	`sharesVested` decimal(18,4) DEFAULT '0',
	`sharesExercised` decimal(18,4) DEFAULT '0',
	`exercisePrice` decimal(18,4),
	`expirationDate` timestamp,
	`earlyExercise` boolean DEFAULT false,
	`principalAmount` decimal(18,2),
	`interestRate` decimal(10,4),
	`valuationCap` decimal(18,2),
	`discountRate` decimal(10,4),
	`maturityDate` timestamp,
	`convertedToShareClassId` int,
	`conversionDate` timestamp,
	`certificateNumber` varchar(64),
	`boardApprovalDate` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `equity_grants_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `equity_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`grantId` int NOT NULL,
	`stakeholderId` int NOT NULL,
	`type` enum('grant','vest','exercise','cancel','expire','convert','transfer','repurchase','forfeit') NOT NULL,
	`shares` decimal(18,4) NOT NULL,
	`pricePerShare` decimal(18,4),
	`totalValue` decimal(18,2),
	`transactionDate` timestamp NOT NULL,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `equity_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `exceptionLog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` int,
	`stepId` int,
	`ruleId` int,
	`exceptionType` varchar(64) NOT NULL,
	`severity` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`title` varchar(500) NOT NULL,
	`description` text,
	`exceptionData` text,
	`entityType` varchar(64),
	`entityId` int,
	`status` enum('open','in_progress','resolved','escalated','ignored') NOT NULL DEFAULT 'open',
	`resolutionType` enum('auto_resolved','ai_resolved','human_resolved','escalated_resolved','ignored'),
	`resolutionAction` text,
	`resolutionNotes` text,
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`financialImpact` decimal(14,2),
	`operationalImpact` varchar(255),
	`detectedAt` timestamp NOT NULL DEFAULT (now()),
	`dueAt` timestamp,
	`escalatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exceptionLog_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `exceptionRules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`exceptionType` enum('quantity_mismatch','price_variance','quality_issue','delivery_delay','stockout','overstock','supplier_unavailable','capacity_constraint','forecast_deviation','payment_issue','documentation_missing','customs_issue','other') NOT NULL,
	`matchConditions` text,
	`varianceThresholdPercent` decimal(5,2),
	`resolutionStrategy` enum('auto_resolve','ai_decide','route_to_human','escalate','apply_default','notify_and_continue','halt_workflow') NOT NULL,
	`autoResolutionAction` text,
	`defaultAction` text,
	`notifyRoles` text,
	`assignToRole` varchar(64),
	`resolveWithinMinutes` int DEFAULT 60,
	`escalateAfterMinutes` int DEFAULT 120,
	`priority` int DEFAULT 100,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exceptionRules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `exercise_requests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`stakeholderId` int NOT NULL,
	`grantId` int NOT NULL,
	`sharesToExercise` decimal(18,4) NOT NULL,
	`exercisePrice` decimal(18,4) NOT NULL,
	`totalCost` decimal(18,2) NOT NULL,
	`exerciseType` enum('cash','cashless','net_exercise') DEFAULT 'cash',
	`status` enum('pending','approved','completed','denied','cancelled') DEFAULT 'pending',
	`requestedAt` timestamp NOT NULL DEFAULT (now()),
	`approvedBy` int,
	`approvedAt` timestamp,
	`completedAt` timestamp,
	`denialReason` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `exercise_requests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `financial_model` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sheetName` varchar(128) NOT NULL,
	`category` varchar(128),
	`metricName` varchar(255) NOT NULL,
	`year` int,
	`month` int,
	`projectedValue` decimal(20,2),
	`actualValue` decimal(20,2),
	`unit` varchar(32) DEFAULT 'USD',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `financial_model_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `freightCostAllocations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`purchaseOrderId` int,
	`shipmentId` int,
	`productId` int NOT NULL,
	`quantity` decimal(15,4) NOT NULL,
	`freightCost` decimal(15,2) NOT NULL,
	`customsDuties` decimal(15,2) DEFAULT '0',
	`insuranceCost` decimal(15,2) DEFAULT '0',
	`handlingFees` decimal(15,2) DEFAULT '0',
	`totalAllocatedCost` decimal(15,2) NOT NULL,
	`allocationMethod` enum('weight','volume','quantity','value','manual') NOT NULL DEFAULT 'quantity',
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `freightCostAllocations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `freight_quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`shipmentId` int,
	`purchaseOrderId` int,
	`carrierName` varchar(255) NOT NULL,
	`carrierEmail` varchar(320),
	`carrierPhone` varchar(32),
	`origin` varchar(500) NOT NULL,
	`destination` varchar(500) NOT NULL,
	`weight` decimal(12,2),
	`dimensions` text,
	`containerType` enum('LTL','FTL','FCL','LCL'),
	`incoterms` enum('FOB','CIF','EXW','DDP','DAP'),
	`quotedPrice` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`transitDays` int,
	`validUntil` timestamp,
	`freight_quote_status` enum('requested','received','selected','expired','declined') NOT NULL DEFAULT 'requested',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `freight_quotes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `fundraising_reminders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`investorId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`dueDate` timestamp NOT NULL,
	`status` enum('pending','completed','cancelled') NOT NULL DEFAULT 'pending',
	`priority` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fundraising_reminders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `grant_bid_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`templateId` int,
	`projectId` int,
	`applicationNumber` varchar(64) NOT NULL,
	`title` varchar(500) NOT NULL,
	`type` enum('grant','procurement_bid','rfp_response','subsidy','tax_incentive') NOT NULL,
	`grantingOrganization` varchar(255),
	`programName` varchar(255),
	`requestedAmount` decimal(15,2),
	`matchingFunds` decimal(15,2),
	`totalProjectCost` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`submissionDeadline` timestamp,
	`submittedAt` timestamp,
	`awardDate` timestamp,
	`projectStartDate` timestamp,
	`projectEndDate` timestamp,
	`status` enum('draft','data_collection','ai_generating','review','approved','submitted','under_review','awarded','rejected','withdrawn') NOT NULL DEFAULT 'draft',
	`formData` text,
	`generatedNarrative` text,
	`dataSourcesUsed` text,
	`submissionMethod` enum('web_form','email','portal','pdf_upload','api') DEFAULT 'pdf_upload',
	`submissionUrl` text,
	`submissionConfirmation` varchar(255),
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`approvedBy` int,
	`approvedAt` timestamp,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_bid_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `grant_bid_documents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`documentType` enum('cover_letter','executive_summary','budget_narrative','financial_statement','org_chart','project_timeline','letter_of_support','tax_document','certification','capability_statement','past_performance','technical_proposal','cost_proposal','attachment','generated_application') NOT NULL,
	`source` enum('auto_generated','erp_export','manual_upload') NOT NULL DEFAULT 'manual_upload',
	`sourceTable` varchar(64),
	`sourceId` int,
	`fileUrl` text,
	`fileSize` int,
	`mimeType` varchar(128),
	`content` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `grant_bid_documents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `grant_bid_field_mappings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`templateId` int NOT NULL,
	`fieldKey` varchar(128) NOT NULL,
	`fieldLabel` varchar(255) NOT NULL,
	`fieldType` enum('text','number','currency','date','textarea','select','file') NOT NULL DEFAULT 'text',
	`dataSource` varchar(64),
	`dataField` varchar(128),
	`dataTransform` text,
	`isRequired` boolean DEFAULT false,
	`validationRule` varchar(255),
	`defaultValue` text,
	`sortOrder` int DEFAULT 0,
	`section` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `grant_bid_field_mappings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `grant_bid_opportunities` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`title` varchar(500) NOT NULL,
	`type` enum('grant','procurement_bid','rfp_response','subsidy','tax_incentive') NOT NULL,
	`organization` varchar(255),
	`programName` varchar(255),
	`description` text,
	`eligibilityCriteria` text,
	`requiredDocuments` text,
	`fundingAmountMin` decimal(15,2),
	`fundingAmountMax` decimal(15,2),
	`matchingRequired` boolean DEFAULT false,
	`matchingPercentage` decimal(5,2),
	`currency` varchar(3) DEFAULT 'USD',
	`openDate` timestamp,
	`deadline` timestamp,
	`awardDate` timestamp,
	`sourceUrl` text,
	`sourceType` enum('web_search','manual','api_feed','email','ai_recommended') NOT NULL DEFAULT 'web_search',
	`matchScore` int,
	`matchReason` text,
	`categories` text,
	`status` enum('discovered','saved','evaluating','applying','applied','not_eligible','expired','dismissed') NOT NULL DEFAULT 'discovered',
	`applicationId` int,
	`notes` text,
	`savedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_bid_opportunities_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `grant_bid_submission_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`action` enum('created','data_collected','narrative_generated','document_attached','submitted_for_review','review_completed','approved','submission_attempted','submission_succeeded','submission_failed','status_updated','awarded','rejected') NOT NULL,
	`details` text,
	`performedBy` int,
	`performedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `grant_bid_submission_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `grant_bid_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`name` varchar(255) NOT NULL,
	`type` enum('grant','procurement_bid','rfp_response','subsidy','tax_incentive') NOT NULL,
	`description` text,
	`sections` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_bid_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `grant_bid_web_form_mappings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`portalName` varchar(255) NOT NULL,
	`portalUrl` text,
	`fieldMappings` text,
	`autoFillScript` text,
	`status` enum('draft','mapped','tested','submitted') NOT NULL DEFAULT 'draft',
	`lastFilledAt` timestamp,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `grant_bid_web_form_mappings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `ingredientCostAlerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ingredientId` int NOT NULL,
	`alertType` enum('price_spike','better_price_found','contract_expiring','quote_below_current','periodic_review','invoice_above_po') NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'info',
	`message` text NOT NULL,
	`details` text,
	`quoteRequestId` int,
	`vendorQuoteId` int,
	`isRead` boolean NOT NULL DEFAULT false,
	`isDismissed` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ingredientCostAlerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `ingredientQuoteRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ingredientId` int NOT NULL,
	`vendorRfqId` int,
	`triggerType` enum('manual','price_spike','contract_expiry','scheduled','cost_review','invoice_variance') NOT NULL,
	`triggerDetails` text,
	`currentCostPerUnit` decimal(12,4),
	`historicalAvgCost` decimal(12,4),
	`targetVendorIds` text,
	`status` enum('pending','rfq_created','quotes_received','analyzed','accepted','cancelled') NOT NULL DEFAULT 'pending',
	`analysisResult` text,
	`acceptedQuoteId` int,
	`costUpdated` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ingredientQuoteRequests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `ingredientVendors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ingredientId` int NOT NULL,
	`vendorId` int NOT NULL,
	`isPrimary` boolean NOT NULL DEFAULT false,
	`unitPrice` decimal(12,4),
	`costUnit` enum('per_lb','per_kg','per_oz','per_each') NOT NULL DEFAULT 'per_kg',
	`contractStartDate` timestamp,
	`contractEndDate` timestamp,
	`minimumOrderQty` decimal(15,4),
	`leadTimeDays` int,
	`paymentTerms` varchar(100),
	`lastQuotedAt` timestamp,
	`lastQuotedPrice` decimal(12,4),
	`quoteValidUntil` timestamp,
	`status` enum('active','inactive','pending_quote') NOT NULL DEFAULT 'active',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ingredientVendors_id` PRIMARY KEY(`id`),
	CONSTRAINT `ingredientVendors_ingredient_vendor_idx` UNIQUE(`ingredientId`,`vendorId`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `inventoryCostLayers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`productId` int NOT NULL,
	`warehouseId` int,
	`purchaseOrderId` int,
	`lotId` int,
	`layerDate` timestamp NOT NULL,
	`originalQuantity` decimal(15,4) NOT NULL,
	`remainingQuantity` decimal(15,4) NOT NULL,
	`unitCost` decimal(15,4) NOT NULL,
	`totalCost` decimal(15,2) NOT NULL,
	`currency` varchar(3) DEFAULT 'USD',
	`status` enum('active','depleted','adjusted') NOT NULL DEFAULT 'active',
	`referenceType` varchar(64),
	`referenceId` int,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventoryCostLayers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `inventoryCostingConfig` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`productId` int NOT NULL,
	`costingMethod` enum('fifo','lifo','weighted_average') NOT NULL DEFAULT 'weighted_average',
	`isActive` boolean NOT NULL DEFAULT true,
	`effectiveDate` timestamp NOT NULL DEFAULT (now()),
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventoryCostingConfig_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `investment_commitments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dataRoomId` int,
	`investorName` varchar(256) NOT NULL,
	`investorEmail` varchar(320) NOT NULL,
	`investorCompany` varchar(256),
	`investorTitle` varchar(128),
	`investmentAmount` decimal(18,2) NOT NULL,
	`shareClassName` varchar(128),
	`instrumentType` enum('equity','safe','convertible_note','warrant') DEFAULT 'safe',
	`valuationCap` decimal(18,2),
	`discountRate` decimal(10,4),
	`notes` text,
	`ndaSigned` boolean DEFAULT false,
	`ndaSignedAt` timestamp,
	`status` enum('interested','committed','docs_sent','signed','funded','completed','declined') DEFAULT 'interested',
	`signedDocumentUrl` text,
	`fundedAt` timestamp,
	`addedToCapTable` boolean DEFAULT false,
	`stakeholderId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `investment_commitments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `investor_investments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`investorId` int NOT NULL,
	`campaignId` int,
	`amount` decimal(18,2) NOT NULL,
	`currency` varchar(8) DEFAULT 'USD',
	`investedAt` timestamp NOT NULL DEFAULT (now()),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `investor_investments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `kpi_goals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`category` varchar(128) NOT NULL,
	`metricName` varchar(255) NOT NULL,
	`year` int NOT NULL,
	`month` int,
	`targetValue` decimal(20,2) NOT NULL,
	`actualValue` decimal(20,2),
	`unit` varchar(32) DEFAULT 'USD',
	`status` enum('on_track','at_risk','behind','exceeded','not_started') DEFAULT 'not_started',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kpi_goals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `negotiationRounds` (
	`id` int AUTO_INCREMENT NOT NULL,
	`negotiationId` int NOT NULL,
	`roundNumber` int NOT NULL,
	`direction` enum('outbound','inbound') NOT NULL,
	`messageType` enum('initial_offer','counter_offer','acceptance','rejection','info_request','final_offer') NOT NULL,
	`proposedUnitPrice` decimal(15,4),
	`proposedPaymentTerms` int,
	`proposedLeadTimeDays` int,
	`proposedMinOrderAmount` decimal(15,2),
	`proposedVolume` decimal(15,2),
	`messageContent` text,
	`aiGeneratedDraft` text,
	`aiReasoning` text,
	`sentAt` timestamp,
	`receivedAt` timestamp,
	`sentBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `negotiationRounds_id` PRIMARY KEY(`id`),
	CONSTRAINT `unique_negotiation_round` UNIQUE(`negotiationId`,`roundNumber`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `offer_letters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`stakeholderId` int,
	`employeeId` int,
	`candidateName` varchar(256) NOT NULL,
	`candidateEmail` varchar(320),
	`position` varchar(256) NOT NULL,
	`department` varchar(128),
	`startDate` timestamp,
	`salary` decimal(12,2),
	`salaryPeriod` enum('annual','monthly','hourly') DEFAULT 'annual',
	`bonus` decimal(12,2),
	`equityShares` decimal(18,4),
	`equityType` varchar(64),
	`vestingMonths` int,
	`cliffMonths` int,
	`benefits` text,
	`reportingTo` varchar(256),
	`location` varchar(256),
	`employmentType` enum('full_time','part_time','contract','intern') DEFAULT 'full_time',
	`letterContent` text,
	`status` enum('draft','sent','viewed','accepted','declined','expired') DEFAULT 'draft',
	`sentAt` timestamp,
	`viewedAt` timestamp,
	`respondedAt` timestamp,
	`expiresAt` timestamp,
	`signatureUrl` text,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `offer_letters_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `quickbooksAccountMappings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`mappingType` enum('cogs_product','cogs_freight','cogs_customs','inventory_asset','freight_expense','income_sales','expense_other') NOT NULL,
	`quickbooksAccountId` varchar(64) NOT NULL,
	`erpCategoryName` varchar(255),
	`isDefault` boolean DEFAULT false,
	`notes` text,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quickbooksAccountMappings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `quickbooksAccounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`quickbooksAccountId` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`accountType` varchar(64),
	`accountSubType` varchar(64),
	`classification` varchar(64),
	`fullyQualifiedName` text,
	`active` boolean DEFAULT true,
	`currentBalance` decimal(15,2),
	`currency` varchar(3) DEFAULT 'USD',
	`lastSyncedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quickbooksAccounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `quickbooksItems` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`quickbooksItemId` varchar(64) NOT NULL,
	`productId` int,
	`name` varchar(255) NOT NULL,
	`sku` varchar(64),
	`type` varchar(32),
	`description` text,
	`unitPrice` decimal(15,2),
	`purchaseCost` decimal(15,2),
	`quantityOnHand` decimal(15,4),
	`incomeAccountId` varchar(64),
	`expenseAccountId` varchar(64),
	`assetAccountId` varchar(64),
	`active` boolean DEFAULT true,
	`lastSyncedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quickbooksItems_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `quickbooksOAuthTokens` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`accessToken` text NOT NULL,
	`refreshToken` text,
	`tokenType` varchar(32) DEFAULT 'Bearer',
	`expiresAt` timestamp,
	`realmId` varchar(64),
	`scope` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `quickbooksOAuthTokens_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `share_classes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`name` varchar(128) NOT NULL,
	`type` enum('common','preferred','convertible_note','safe','warrant','option_pool') NOT NULL,
	`authorizedShares` decimal(18,4),
	`parValue` decimal(18,6) DEFAULT '0.0001',
	`pricePerShare` decimal(18,4),
	`liquidationPreference` decimal(10,4) DEFAULT '1',
	`liquidationMultiple` decimal(10,4) DEFAULT '1',
	`isParticipating` boolean DEFAULT false,
	`participationCap` decimal(10,4),
	`conversionRatio` decimal(10,4) DEFAULT '1',
	`votingRights` boolean DEFAULT true,
	`dividendRate` decimal(10,4),
	`antidilutionProtection` enum('none','broad_weighted_average','narrow_weighted_average','full_ratchet') DEFAULT 'none',
	`boardSeats` int DEFAULT 0,
	`seniorityRank` int DEFAULT 0,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `share_classes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `stakeholders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`name` varchar(256) NOT NULL,
	`email` varchar(320),
	`type` enum('founder','employee','investor','advisor','board_member','contractor') NOT NULL,
	`title` varchar(128),
	`relationship` varchar(128),
	`address` text,
	`taxId` varchar(64),
	`accreditedInvestor` boolean DEFAULT false,
	`status` enum('active','inactive','terminated','departed') DEFAULT 'active',
	`terminationDate` timestamp,
	`notes` text,
	`userId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `stakeholders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `supplierPerformance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`vendorId` int NOT NULL,
	`metricMonth` varchar(7) NOT NULL,
	`totalOrders` int DEFAULT 0,
	`onTimeDeliveries` int DEFAULT 0,
	`lateDeliveries` int DEFAULT 0,
	`averageLeadTimeDays` decimal(8,2),
	`leadTimeVarianceDays` decimal(8,2),
	`totalItemsReceived` int DEFAULT 0,
	`qualityPassCount` int DEFAULT 0,
	`qualityFailCount` int DEFAULT 0,
	`qualityPassRate` decimal(5,2),
	`quantityMatchCount` int DEFAULT 0,
	`quantityVarianceCount` int DEFAULT 0,
	`totalSpend` decimal(18,2),
	`averagePriceVariancePercent` decimal(6,2),
	`averageResponseTimeHours` decimal(8,2),
	`issuesReported` int DEFAULT 0,
	`issuesResolved` int DEFAULT 0,
	`deliveryScore` decimal(5,2),
	`qualityScore` decimal(5,2),
	`priceScore` decimal(5,2),
	`responsiveScore` decimal(5,2),
	`overallScore` decimal(5,2),
	`aiAssessment` text,
	`recommendedActions` text,
	`riskLevel` enum('low','medium','high') DEFAULT 'low',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `supplierPerformance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `supplyChainEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventType` enum('inventory_low','inventory_critical','inventory_excess','inventory_expiring','inventory_received','inventory_adjustment','order_created','order_confirmed','order_shipped','order_delivered','order_cancelled','po_created','po_sent','po_confirmed','po_shipped','po_received','po_discrepancy','work_order_created','production_started','production_completed','production_issue','yield_variance','quote_received','price_change','lead_time_change','supplier_issue','shipment_booked','shipment_picked_up','shipment_delayed','shipment_delivered','customs_hold','quality_issue','inspection_failed','inspection_passed','invoice_received','payment_due','payment_overdue','forecast_generated','demand_spike','demand_drop','workflow_completed','workflow_failed','approval_needed','escalation_triggered') NOT NULL,
	`severity` enum('info','warning','error','critical') NOT NULL DEFAULT 'info',
	`sourceSystem` varchar(64),
	`sourceEntityType` varchar(64),
	`sourceEntityId` int,
	`eventData` text,
	`summary` varchar(500),
	`isProcessed` boolean DEFAULT false,
	`processedAt` timestamp,
	`processedByWorkflowId` int,
	`processedByRunId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `supplyChainEvents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `supplyChainWorkflows` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`workflowType` enum('demand_forecasting','production_planning','material_requirements','procurement','inventory_reorder','inventory_transfer','inventory_optimization','work_order_generation','production_scheduling','freight_procurement','shipment_tracking','order_fulfillment','supplier_management','quality_inspection','invoice_matching','payment_processing','exception_handling','vendor_quote_procurement','vendor_quote_analysis','custom') NOT NULL,
	`triggerType` enum('scheduled','event','threshold','manual','continuous') NOT NULL DEFAULT 'scheduled',
	`cronSchedule` varchar(64),
	`triggerEvents` text,
	`thresholdConfig` text,
	`executionConfig` text,
	`maxConcurrentRuns` int DEFAULT 1,
	`timeoutMinutes` int DEFAULT 60,
	`retryAttempts` int DEFAULT 3,
	`retryDelayMinutes` int DEFAULT 5,
	`requiresApproval` boolean DEFAULT false,
	`autoApproveThreshold` decimal(14,2),
	`approvalRoles` text,
	`escalationMinutes` int DEFAULT 60,
	`escalationRoles` text,
	`dependsOnWorkflows` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastRunAt` timestamp,
	`nextScheduledRun` timestamp,
	`successCount` int DEFAULT 0,
	`failureCount` int DEFAULT 0,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `supplyChainWorkflows_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `team_invites` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`email` varchar(320) NOT NULL,
	`name` varchar(256),
	`role` enum('user','admin','finance','ops','legal','exec','sales','copacker','vendor','contractor') NOT NULL DEFAULT 'user',
	`invitedBy` int NOT NULL,
	`token` varchar(128) NOT NULL,
	`status` enum('pending','accepted','expired','cancelled') DEFAULT 'pending',
	`expiresAt` timestamp NOT NULL,
	`acceptedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `team_invites_id` PRIMARY KEY(`id`),
	CONSTRAINT `team_invites_token_unique` UNIQUE(`token`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `time_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`userId` int NOT NULL,
	`projectId` int,
	`taskDescription` varchar(512) NOT NULL,
	`date` timestamp NOT NULL,
	`hours` decimal(8,2) NOT NULL,
	`hourlyRate` decimal(10,2),
	`totalAmount` decimal(12,2),
	`category` enum('development','design','consulting','management','operations','admin','sales','support','other') DEFAULT 'other',
	`billable` boolean DEFAULT true,
	`status` enum('draft','submitted','approved','invoiced','paid') DEFAULT 'draft',
	`approvedBy` int,
	`approvedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `time_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `time_invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`userId` int NOT NULL,
	`invoiceNumber` varchar(64) NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalHours` decimal(10,2) NOT NULL,
	`hourlyRate` decimal(10,2) NOT NULL,
	`subtotal` decimal(12,2) NOT NULL,
	`taxAmount` decimal(12,2) DEFAULT '0',
	`totalAmount` decimal(12,2) NOT NULL,
	`status` enum('draft','submitted','approved','sent','paid') DEFAULT 'draft',
	`submittedAt` timestamp,
	`approvedBy` int,
	`approvedAt` timestamp,
	`sentAt` timestamp,
	`sentTo` varchar(320),
	`paidAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `time_invoices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `transactional_email_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` enum('QUOTE','PO','SHIPMENT','ALERT','RFQ','INVOICE','PAYMENT_REMINDER','WELCOME','GENERAL') NOT NULL,
	`providerTemplateId` varchar(128) NOT NULL,
	`description` text,
	`variablesSchema` json,
	`defaultSubject` varchar(512),
	`isActive` boolean DEFAULT true,
	`createdBy` int,
	`updatedBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `transactional_email_templates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `vendor_negotiation_products` (
	`id` bigint unsigned AUTO_INCREMENT NOT NULL,
	`negotiation_id` int NOT NULL,
	`product_id` int,
	`raw_material_id` int,
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `vendor_negotiation_products_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `vendorNegotiations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`companyId` int,
	`vendorId` int NOT NULL,
	`negotiationNumber` varchar(64) NOT NULL,
	`title` varchar(255) NOT NULL,
	`type` enum('price_reduction','volume_discount','payment_terms','lead_time','contract_renewal','new_contract') NOT NULL,
	`status` enum('draft','analyzing','ready','in_progress','counter_offered','accepted','rejected','expired') NOT NULL DEFAULT 'draft',
	`priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
	`productIds` text,
	`rawMaterialIds` text,
	`currentUnitPrice` decimal(15,4),
	`currentPaymentTerms` int,
	`currentLeadTimeDays` int,
	`currentMinOrderAmount` decimal(15,2),
	`currentAnnualVolume` decimal(15,2),
	`targetUnitPrice` decimal(15,4),
	`targetPaymentTerms` int,
	`targetLeadTimeDays` int,
	`targetMinOrderAmount` decimal(15,2),
	`targetAnnualVolume` decimal(15,2),
	`agreedUnitPrice` decimal(15,4),
	`agreedPaymentTerms` int,
	`agreedLeadTimeDays` int,
	`agreedMinOrderAmount` decimal(15,2),
	`agreedAnnualVolume` decimal(15,2),
	`aiAnalysis` text,
	`aiStrategy` text,
	`aiConfidenceScore` decimal(5,2),
	`estimatedSavings` decimal(15,2),
	`estimatedSavingsPercent` decimal(8,4),
	`lastEmailSentAt` timestamp,
	`lastResponseAt` timestamp,
	`negotiationRounds` int DEFAULT 0,
	`maxRounds` int DEFAULT 5,
	`expiresAt` timestamp,
	`completedAt` timestamp,
	`initiatedBy` int,
	`assignedTo` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vendorNegotiations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `whatsapp_messages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contactId` int,
	`messageId` varchar(128),
	`conversationId` varchar(128),
	`whatsappNumber` varchar(32) NOT NULL,
	`contactName` varchar(255),
	`direction` enum('inbound','outbound') NOT NULL,
	`messageType` enum('text','image','video','audio','document','location','contact','template') DEFAULT 'text',
	`content` text,
	`mediaUrl` text,
	`mediaType` varchar(128),
	`status` enum('pending','sent','delivered','read','failed') DEFAULT 'pending',
	`sentAt` timestamp,
	`deliveredAt` timestamp,
	`readAt` timestamp,
	`failedReason` text,
	`templateName` varchar(128),
	`templateParams` text,
	`aiProcessed` boolean DEFAULT false,
	`sentiment` enum('positive','neutral','negative'),
	`aiSummary` text,
	`aiSuggestedReply` text,
	`relatedEntityType` varchar(50),
	`relatedEntityId` int,
	`sentBy` int,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `whatsapp_messages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `workflowApprovalQueue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` int NOT NULL,
	`approvalType` enum('purchase_order','work_order','inventory_transfer','freight_booking','payment','price_change','vendor_selection','exception_override','forecast_adjustment','workflow_result') NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`monetaryValue` decimal(14,2),
	`currency` varchar(3) DEFAULT 'USD',
	`contextData` text,
	`aiRecommendation` text,
	`aiConfidence` decimal(5,2),
	`riskAssessment` enum('low','medium','high','critical') DEFAULT 'low',
	`relatedEntityType` varchar(64),
	`relatedEntityId` int,
	`status` enum('pending','approved','rejected','auto_approved','escalated','expired') NOT NULL DEFAULT 'pending',
	`assignedToRoles` text,
	`assignedToUsers` text,
	`currentAssignee` int,
	`requestedAt` timestamp NOT NULL DEFAULT (now()),
	`dueAt` timestamp,
	`escalateAt` timestamp,
	`escalatedAt` timestamp,
	`escalationLevel` int DEFAULT 0,
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`resolutionNotes` text,
	`wasAutoApproved` boolean DEFAULT false,
	`autoApprovalReason` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workflowApprovalQueue_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `workflowMetrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workflowId` int NOT NULL,
	`metricDate` timestamp NOT NULL,
	`totalRuns` int DEFAULT 0,
	`successfulRuns` int DEFAULT 0,
	`failedRuns` int DEFAULT 0,
	`averageDurationMs` int,
	`maxDurationMs` int,
	`autoApprovedCount` int DEFAULT 0,
	`manualApprovedCount` int DEFAULT 0,
	`rejectedCount` int DEFAULT 0,
	`averageApprovalTimeMs` int,
	`escalationCount` int DEFAULT 0,
	`itemsProcessed` int DEFAULT 0,
	`totalValueProcessed` decimal(18,2),
	`exceptionsHandled` int DEFAULT 0,
	`aiDecisionCount` int DEFAULT 0,
	`aiOverrideCount` int DEFAULT 0,
	`averageAiConfidence` decimal(5,2),
	`totalTokensUsed` int DEFAULT 0,
	`estimatedTimeSavedMinutes` int,
	`estimatedCostSavings` decimal(14,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workflowMetrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `workflowNotifications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` int,
	`notificationType` enum('info','warning','error','approval_needed','approval_completed','exception','milestone','completion') NOT NULL,
	`title` varchar(500) NOT NULL,
	`message` text,
	`targetRoles` text,
	`targetUserIds` text,
	`sendEmail` boolean DEFAULT false,
	`sendInApp` boolean DEFAULT true,
	`sendSlack` boolean DEFAULT false,
	`isRead` boolean DEFAULT false,
	`readBy` int,
	`readAt` timestamp,
	`actionUrl` varchar(500),
	`actionLabel` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `workflowNotifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `workflowRuns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`workflowId` int NOT NULL,
	`runNumber` varchar(64) NOT NULL,
	`status` enum('queued','running','awaiting_approval','approved','rejected','completed','failed','cancelled','timed_out') NOT NULL DEFAULT 'queued',
	`triggeredBy` enum('schedule','event','threshold','manual','dependency') NOT NULL,
	`triggerData` text,
	`triggeredByUserId` int,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`durationMs` int,
	`totalSteps` int DEFAULT 0,
	`completedSteps` int DEFAULT 0,
	`currentStepName` varchar(255),
	`progressPercent` int DEFAULT 0,
	`inputData` text,
	`outputData` text,
	`errorMessage` text,
	`errorDetails` text,
	`itemsProcessed` int DEFAULT 0,
	`itemsSucceeded` int DEFAULT 0,
	`itemsFailed` int DEFAULT 0,
	`totalValue` decimal(14,2),
	`attemptNumber` int DEFAULT 1,
	`parentRunId` int,
	`approvalRequestedAt` timestamp,
	`approvedBy` int,
	`approvedAt` timestamp,
	`rejectedBy` int,
	`rejectedAt` timestamp,
	`rejectionReason` text,
	`escalatedAt` timestamp,
	`escalatedTo` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `workflowRuns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS `workflowSteps` (
	`id` int AUTO_INCREMENT NOT NULL,
	`runId` int NOT NULL,
	`stepNumber` int NOT NULL,
	`stepName` varchar(255) NOT NULL,
	`stepType` enum('data_fetch','ai_analysis','ai_decision','calculation','validation','create_record','update_record','send_email','send_notification','api_call','wait_approval','condition_check','loop_start','loop_end','parallel_start','parallel_end','subprocess') NOT NULL,
	`status` enum('pending','running','completed','failed','skipped','awaiting_input') NOT NULL DEFAULT 'pending',
	`startedAt` timestamp,
	`completedAt` timestamp,
	`durationMs` int,
	`inputData` text,
	`outputData` text,
	`errorMessage` text,
	`aiPrompt` text,
	`aiResponse` text,
	`aiConfidence` decimal(5,2),
	`aiTokensUsed` int,
	`createdEntityType` varchar(64),
	`createdEntityId` int,
	`modifiedEntityType` varchar(64),
	`modifiedEntityId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `workflowSteps_id` PRIMARY KEY(`id`)
);
