import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { toast } from "sonner";
import {
  Mail, Search, Sparkles, Pen, Tags, FolderOpen, ListTodo,
  Clock, Send, Archive, Star, RefreshCw, Loader2, Plus,
  Inbox, ChevronRight, ChevronDown, MoreHorizontal, Zap,
  Globe, CheckCircle2, AlertCircle, ArrowUpCircle, MinusCircle,
  ArrowDownCircle, Reply, Trash2, Eye, MessageSquare,
  FileText, Wand2, SlidersHorizontal, Timer, Bot, Languages,
  BookOpen, GripVertical, Package, X
} from "lucide-react";

// ============================================
// TYPES
// ============================================

type ActivePanel = "inbox" | "search" | "compose" | "todos" | "bundles" | "settings";

// Category display configuration
const categoryConfig: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
  receipt: { label: "Receipt", color: "bg-green-100 text-green-800 dark:bg-green-900/50 dark:text-green-300", icon: <FileText className="h-3 w-3" /> },
  purchase_order: { label: "Purchase Order", color: "bg-blue-100 text-blue-800 dark:bg-blue-900/50 dark:text-blue-300", icon: <Package className="h-3 w-3" /> },
  invoice: { label: "Invoice", color: "bg-orange-100 text-orange-800 dark:bg-orange-900/50 dark:text-orange-300", icon: <FileText className="h-3 w-3" /> },
  shipping_confirmation: { label: "Shipping", color: "bg-purple-100 text-purple-800 dark:bg-purple-900/50 dark:text-purple-300", icon: <Package className="h-3 w-3" /> },
  general: { label: "General", color: "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300", icon: <Mail className="h-3 w-3" /> },
};

const priorityConfig: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
  high: { label: "High", color: "text-red-500", icon: <ArrowUpCircle className="h-3 w-3" /> },
  medium: { label: "Medium", color: "text-yellow-500", icon: <MinusCircle className="h-3 w-3" /> },
  low: { label: "Low", color: "text-green-500", icon: <ArrowDownCircle className="h-3 w-3" /> },
};

// ============================================
// MAIN COMPONENT
// ============================================

export default function EmailHub() {
  const [activePanel, setActivePanel] = useState<ActivePanel>("inbox");
  const [selectedEmailId, setSelectedEmailId] = useState<number | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [activeSplit, setActiveSplit] = useState("all");
  const [showCompose, setShowCompose] = useState(false);
  const [composePrompt, setComposePrompt] = useState("");
  const [composeRecipient, setComposeRecipient] = useState("");
  const [composeRecipientName, setComposeRecipientName] = useState("");
  const [expandedBundles, setExpandedBundles] = useState<Set<number>>(new Set());

  // ============================================
  // DATA QUERIES
  // ============================================

  const emailsQuery = trpc.emailScanning.list.useQuery();
  const inboxSplitsQuery = trpc.shortwaveEmail.getInboxSplits.useQuery();
  const bundlesQuery = trpc.shortwaveEmail.getBundles.useQuery();
  const todosQuery = trpc.shortwaveEmail.getEmailTodos.useQuery();
  const labelsQuery = trpc.shortwaveEmail.getSmartLabels.useQuery();
  const writingProfileQuery = trpc.shortwaveEmail.getWritingProfile.useQuery();
  const draftsQuery = trpc.shortwaveEmail.getDrafts.useQuery();

  // ============================================
  // MUTATIONS
  // ============================================

  const summarizeMutation = trpc.shortwaveEmail.summarizeThread.useMutation({
    onSuccess: (data) => {
      toast.success("Thread summarized");
      setSummaryResult(data);
    },
    onError: (err) => toast.error(err.message),
  });

  const ghostwriteMutation = trpc.shortwaveEmail.ghostwrite.useMutation({
    onSuccess: (data) => {
      toast.success("Draft generated by Ghostwriter");
      setGhostwriteResult(data);
    },
    onError: (err) => toast.error(err.message),
  });

  const learnStyleMutation = trpc.shortwaveEmail.learnStyle.useMutation({
    onSuccess: () => {
      toast.success("Writing style learned successfully");
      writingProfileQuery.refetch();
    },
    onError: (err) => toast.error(err.message),
  });

  const aiSearchMutation = trpc.shortwaveEmail.aiSearch.useMutation({
    onSuccess: (data) => setSearchResult(data),
    onError: (err) => toast.error(err.message),
  });

  const organizeMutation = trpc.shortwaveEmail.organizeInbox.useMutation({
    onSuccess: (data) => {
      toast.success(`Found ${data.length} organization suggestions`);
      setOrganizeSuggestions(data);
    },
    onError: (err) => toast.error(err.message),
  });

  const extractTodosMutation = trpc.shortwaveEmail.extractTodos.useMutation({
    onSuccess: (data) => {
      toast.success(`Extracted ${data.created.length} todos`);
      todosQuery.refetch();
    },
    onError: (err) => toast.error(err.message),
  });

  const createTodoMutation = trpc.shortwaveEmail.createEmailTodo.useMutation({
    onSuccess: () => {
      todosQuery.refetch();
      toast.success("Todo created");
    },
  });

  const updateTodoMutation = trpc.shortwaveEmail.updateEmailTodo.useMutation({
    onSuccess: () => todosQuery.refetch(),
  });

  const translateMutation = trpc.shortwaveEmail.translate.useMutation({
    onSuccess: (data) => {
      toast.success(`Translated from ${data.sourceLanguage}`);
      setTranslationResult(data);
    },
    onError: (err) => toast.error(err.message),
  });

  const createBundleMutation = trpc.shortwaveEmail.createBundle.useMutation({
    onSuccess: () => {
      bundlesQuery.refetch();
      toast.success("Bundle created");
    },
  });

  const createSplitMutation = trpc.shortwaveEmail.createInboxSplit.useMutation({
    onSuccess: () => {
      inboxSplitsQuery.refetch();
      toast.success("Inbox split created");
    },
  });

  const autoLabelMutation = trpc.shortwaveEmail.autoLabelEmail.useMutation({
    onSuccess: (data) => {
      toast.success(`Applied ${data.length} labels`);
    },
  });

  // ============================================
  // LOCAL STATE FOR AI RESULTS
  // ============================================

  const [summaryResult, setSummaryResult] = useState<any>(null);
  const [ghostwriteResult, setGhostwriteResult] = useState<any>(null);
  const [searchResult, setSearchResult] = useState<any>(null);
  const [organizeSuggestions, setOrganizeSuggestions] = useState<any[]>([]);
  const [translationResult, setTranslationResult] = useState<any>(null);
  const [showNewBundleDialog, setShowNewBundleDialog] = useState(false);
  const [showNewSplitDialog, setShowNewSplitDialog] = useState(false);
  const [newBundleName, setNewBundleName] = useState("");
  const [newBundleMatchType, setNewBundleMatchType] = useState<string>("sender_domain");
  const [newSplitName, setNewSplitName] = useState("");
  const [newSplitFilterType, setNewSplitFilterType] = useState<string>("important");
  const [translateLang, setTranslateLang] = useState("Spanish");

  // Simulated emails for the inbox view (using inbound emails data)
  const emails = (emailsQuery.data as any[]) || [];
  const selectedEmail = emails.find((e: any) => e.id === selectedEmailId);

  const splits = inboxSplitsQuery.data || [];
  const bundles = bundlesQuery.data || [];
  const todos = (todosQuery.data || []) as any[];
  const labels = labelsQuery.data || [];
  const drafts = draftsQuery.data || [];

  // ============================================
  // RENDER
  // ============================================

  return (
    <div className="flex flex-col h-[calc(100vh-4rem)]">
      {/* Top Bar */}
      <div className="flex items-center justify-between border-b px-4 py-2 bg-background">
        <div className="flex items-center gap-2">
          <Mail className="h-5 w-5 text-primary" />
          <h1 className="text-lg font-semibold">AI Email Hub</h1>
          <Badge variant="secondary" className="text-xs">
            <Sparkles className="h-3 w-3 mr-1" />
            Shortwave-powered
          </Badge>
        </div>
        <div className="flex items-center gap-2">
          {/* AI Search Bar */}
          <div className="relative w-96">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Ask AI anything about your emails..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && searchQuery.trim()) {
                  aiSearchMutation.mutate({ query: searchQuery });
                  setActivePanel("search");
                }
              }}
              className="pl-9 pr-20"
            />
            {searchQuery && (
              <Button
                size="sm"
                variant="ghost"
                className="absolute right-1 top-1/2 -translate-y-1/2 h-7 text-xs"
                onClick={() => {
                  aiSearchMutation.mutate({ query: searchQuery });
                  setActivePanel("search");
                }}
                disabled={aiSearchMutation.isPending}
              >
                {aiSearchMutation.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />}
                <span className="ml-1">Ask AI</span>
              </Button>
            )}
          </div>
          <Button variant="outline" size="sm" onClick={() => setShowCompose(true)}>
            <Pen className="h-4 w-4 mr-1" />
            Compose
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => organizeMutation.mutate()}
            disabled={organizeMutation.isPending}
          >
            {organizeMutation.isPending ? (
              <Loader2 className="h-4 w-4 mr-1 animate-spin" />
            ) : (
              <Zap className="h-4 w-4 mr-1" />
            )}
            Organize
          </Button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex flex-1 overflow-hidden">
        {/* Left Sidebar - Navigation */}
        <div className="w-52 border-r bg-muted/30 flex flex-col">
          <div className="p-2 space-y-0.5">
            <SidebarItem
              icon={<Inbox className="h-4 w-4" />}
              label="Inbox"
              active={activePanel === "inbox"}
              onClick={() => setActivePanel("inbox")}
              count={emails.length}
            />
            <SidebarItem
              icon={<Search className="h-4 w-4" />}
              label="AI Search"
              active={activePanel === "search"}
              onClick={() => setActivePanel("search")}
            />
            <SidebarItem
              icon={<Pen className="h-4 w-4" />}
              label="Ghostwriter"
              active={activePanel === "compose"}
              onClick={() => setActivePanel("compose")}
              badge={<Sparkles className="h-3 w-3 text-amber-500" />}
            />
            <SidebarItem
              icon={<ListTodo className="h-4 w-4" />}
              label="Todos"
              active={activePanel === "todos"}
              onClick={() => setActivePanel("todos")}
              count={todos.filter((t: any) => t.status === "pending").length}
            />
            <SidebarItem
              icon={<FolderOpen className="h-4 w-4" />}
              label="Bundles"
              active={activePanel === "bundles"}
              onClick={() => setActivePanel("bundles")}
              count={bundles.length}
            />
            <SidebarItem
              icon={<SlidersHorizontal className="h-4 w-4" />}
              label="Settings"
              active={activePanel === "settings"}
              onClick={() => setActivePanel("settings")}
            />
          </div>

          <Separator className="my-2" />

          {/* Smart Labels */}
          <div className="px-2">
            <div className="flex items-center justify-between px-2 py-1">
              <span className="text-xs font-medium text-muted-foreground uppercase">Smart Labels</span>
              <Tags className="h-3 w-3 text-muted-foreground" />
            </div>
            {(labels as any[]).map((label: any) => (
              <div
                key={label.id}
                className="flex items-center gap-2 px-2 py-1 text-sm rounded hover:bg-muted cursor-pointer"
              >
                <div
                  className="w-2 h-2 rounded-full"
                  style={{ backgroundColor: label.color || "#6b7280" }}
                />
                <span className="truncate">{label.name}</span>
              </div>
            ))}
          </div>

          <Separator className="my-2" />

          {/* Drafts */}
          <div className="px-2">
            <div className="flex items-center justify-between px-2 py-1">
              <span className="text-xs font-medium text-muted-foreground uppercase">AI Drafts</span>
              <Badge variant="secondary" className="text-xs h-4 px-1">{drafts.length}</Badge>
            </div>
            {(drafts as any[]).slice(0, 5).map((draft: any) => (
              <div key={draft.id} className="px-2 py-1 text-xs text-muted-foreground truncate hover:bg-muted rounded cursor-pointer">
                {draft.subject || draft.prompt || "Untitled draft"}
              </div>
            ))}
          </div>
        </div>

        {/* Main Panel */}
        <div className="flex-1 flex flex-col overflow-hidden">
          {activePanel === "inbox" && (
            <InboxPanel
              emails={emails}
              selectedEmailId={selectedEmailId}
              setSelectedEmailId={setSelectedEmailId}
              selectedEmail={selectedEmail}
              splits={splits}
              activeSplit={activeSplit}
              setActiveSplit={setActiveSplit}
              bundles={bundles}
              expandedBundles={expandedBundles}
              setExpandedBundles={setExpandedBundles}
              onSummarize={(emailIds: number[]) => summarizeMutation.mutate({ emailIds })}
              summaryResult={summaryResult}
              isSummarizing={summarizeMutation.isPending}
              onExtractTodos={(emailId: number) => extractTodosMutation.mutate({ emailId })}
              isExtractingTodos={extractTodosMutation.isPending}
              onAutoLabel={(emailId: number) => autoLabelMutation.mutate({ emailId })}
              onTranslate={(text: string) => translateMutation.mutate({ text, targetLanguage: translateLang })}
              translationResult={translationResult}
              translateLang={translateLang}
              setTranslateLang={setTranslateLang}
              organizeSuggestions={organizeSuggestions}
              onGhostwriteReply={(emailId: number) => {
                setActivePanel("compose");
                setComposePrompt(`Reply to this email`);
              }}
            />
          )}

          {activePanel === "search" && (
            <SearchPanel
              searchQuery={searchQuery}
              setSearchQuery={setSearchQuery}
              searchResult={searchResult}
              isSearching={aiSearchMutation.isPending}
              onSearch={(q: string) => aiSearchMutation.mutate({ query: q })}
              onSelectEmail={(id: number) => {
                setSelectedEmailId(id);
                setActivePanel("inbox");
              }}
            />
          )}

          {activePanel === "compose" && (
            <ComposePanel
              composePrompt={composePrompt}
              setComposePrompt={setComposePrompt}
              composeRecipient={composeRecipient}
              setComposeRecipient={setComposeRecipient}
              composeRecipientName={composeRecipientName}
              setComposeRecipientName={setComposeRecipientName}
              ghostwriteResult={ghostwriteResult}
              isGenerating={ghostwriteMutation.isPending}
              onGhostwrite={() => {
                ghostwriteMutation.mutate({
                  prompt: composePrompt,
                  recipientName: composeRecipientName || undefined,
                  recipientEmail: composeRecipient || undefined,
                });
              }}
              writingProfile={writingProfileQuery.data}
              onLearnStyle={() => learnStyleMutation.mutate()}
              isLearning={learnStyleMutation.isPending}
            />
          )}

          {activePanel === "todos" && (
            <TodosPanel
              todos={todos}
              onUpdateTodo={(id: number, status: string) =>
                updateTodoMutation.mutate({ id, status: status as any })
              }
              onCreateTodo={(emailId: number, title: string) =>
                createTodoMutation.mutate({ emailId, title })
              }
            />
          )}

          {activePanel === "bundles" && (
            <BundlesPanel
              bundles={bundles}
              showNewBundleDialog={showNewBundleDialog}
              setShowNewBundleDialog={setShowNewBundleDialog}
              newBundleName={newBundleName}
              setNewBundleName={setNewBundleName}
              newBundleMatchType={newBundleMatchType}
              setNewBundleMatchType={setNewBundleMatchType}
              onCreateBundle={() => {
                createBundleMutation.mutate({
                  name: newBundleName,
                  matchType: newBundleMatchType as any,
                });
                setShowNewBundleDialog(false);
                setNewBundleName("");
              }}
              splits={splits}
              showNewSplitDialog={showNewSplitDialog}
              setShowNewSplitDialog={setShowNewSplitDialog}
              newSplitName={newSplitName}
              setNewSplitName={setNewSplitName}
              newSplitFilterType={newSplitFilterType}
              setNewSplitFilterType={setNewSplitFilterType}
              onCreateSplit={() => {
                createSplitMutation.mutate({
                  name: newSplitName,
                  filterType: newSplitFilterType as any,
                });
                setShowNewSplitDialog(false);
                setNewSplitName("");
              }}
            />
          )}

          {activePanel === "settings" && (
            <SettingsPanel
              writingProfile={writingProfileQuery.data}
              onLearnStyle={() => learnStyleMutation.mutate()}
              isLearning={learnStyleMutation.isPending}
            />
          )}
        </div>
      </div>

      {/* Compose Dialog (Quick Compose) */}
      <Dialog open={showCompose} onOpenChange={setShowCompose}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-amber-500" />
              Ghostwriter Compose
            </DialogTitle>
            <DialogDescription>
              Tell the AI what to write and it will match your personal style.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>To</Label>
                <Input
                  placeholder="recipient@email.com"
                  value={composeRecipient}
                  onChange={(e) => setComposeRecipient(e.target.value)}
                />
              </div>
              <div>
                <Label>Recipient Name</Label>
                <Input
                  placeholder="John Smith"
                  value={composeRecipientName}
                  onChange={(e) => setComposeRecipientName(e.target.value)}
                />
              </div>
            </div>
            <div>
              <Label>What should the email say?</Label>
              <Textarea
                placeholder="e.g., Follow up on the pricing proposal we discussed last week, ask about timeline for Q2 delivery..."
                value={composePrompt}
                onChange={(e) => setComposePrompt(e.target.value)}
                rows={3}
              />
            </div>
            {ghostwriteResult && (
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label>Generated Email</Label>
                  <Badge variant="outline">Style match: {ghostwriteResult.styleMatchScore}%</Badge>
                </div>
                <div className="p-3 bg-muted rounded-md text-sm">
                  <p className="font-medium mb-1">Subject: {ghostwriteResult.subject}</p>
                  <Separator className="my-2" />
                  <p className="whitespace-pre-wrap">{ghostwriteResult.body}</p>
                </div>
                {ghostwriteResult.alternatives?.length > 0 && (
                  <div>
                    <Label className="text-xs text-muted-foreground">Alternative versions:</Label>
                    {ghostwriteResult.alternatives.map((alt: any, i: number) => (
                      <div key={i} className="p-2 bg-muted/50 rounded text-xs mt-1">
                        <Badge variant="outline" className="text-xs mb-1">{alt.tone}</Badge>
                        <p className="whitespace-pre-wrap">{alt.body}</p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCompose(false)}>Cancel</Button>
            <Button
              onClick={() =>
                ghostwriteMutation.mutate({
                  prompt: composePrompt,
                  recipientName: composeRecipientName || undefined,
                  recipientEmail: composeRecipient || undefined,
                })
              }
              disabled={!composePrompt || ghostwriteMutation.isPending}
            >
              {ghostwriteMutation.isPending ? (
                <Loader2 className="h-4 w-4 mr-1 animate-spin" />
              ) : (
                <Wand2 className="h-4 w-4 mr-1" />
              )}
              Generate with Ghostwriter
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// ============================================
// SIDEBAR ITEM COMPONENT
// ============================================

function SidebarItem({
  icon,
  label,
  active,
  onClick,
  count,
  badge,
}: {
  icon: React.ReactNode;
  label: string;
  active: boolean;
  onClick: () => void;
  count?: number;
  badge?: React.ReactNode;
}) {
  return (
    <button
      onClick={onClick}
      className={`w-full flex items-center gap-2 px-2 py-1.5 rounded text-sm transition-colors ${
        active ? "bg-primary/10 text-primary font-medium" : "text-muted-foreground hover:bg-muted hover:text-foreground"
      }`}
    >
      {icon}
      <span className="flex-1 text-left truncate">{label}</span>
      {badge}
      {count !== undefined && count > 0 && (
        <Badge variant="secondary" className="text-xs h-4 min-w-[1.25rem] px-1 justify-center">
          {count}
        </Badge>
      )}
    </button>
  );
}

// ============================================
// INBOX PANEL
// ============================================

function InboxPanel({
  emails,
  selectedEmailId,
  setSelectedEmailId,
  selectedEmail,
  splits,
  activeSplit,
  setActiveSplit,
  bundles,
  expandedBundles,
  setExpandedBundles,
  onSummarize,
  summaryResult,
  isSummarizing,
  onExtractTodos,
  isExtractingTodos,
  onAutoLabel,
  onTranslate,
  translationResult,
  translateLang,
  setTranslateLang,
  organizeSuggestions,
  onGhostwriteReply,
}: any) {
  return (
    <div className="flex flex-1 overflow-hidden">
      {/* Email List */}
      <div className="w-96 border-r flex flex-col">
        {/* Splits Tabs */}
        <div className="flex items-center gap-1 px-2 py-1.5 border-b overflow-x-auto">
          <button
            className={`px-2 py-1 text-xs rounded whitespace-nowrap ${
              activeSplit === "all" ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"
            }`}
            onClick={() => setActiveSplit("all")}
          >
            All Mail
          </button>
          {(splits as any[]).map((split: any) => (
            <button
              key={split.id}
              className={`px-2 py-1 text-xs rounded whitespace-nowrap ${
                activeSplit === split.id.toString()
                  ? "bg-primary text-primary-foreground"
                  : "text-muted-foreground hover:bg-muted"
              }`}
              onClick={() => setActiveSplit(split.id.toString())}
            >
              {split.name}
            </button>
          ))}
        </div>

        {/* Organization Suggestions Banner */}
        {organizeSuggestions.length > 0 && (
          <div className="px-3 py-2 bg-amber-50 dark:bg-amber-900/20 border-b">
            <div className="flex items-center gap-1 text-xs font-medium text-amber-800 dark:text-amber-300">
              <Zap className="h-3 w-3" />
              {organizeSuggestions.length} suggestions to organize your inbox
            </div>
            {organizeSuggestions.slice(0, 3).map((s: any, i: number) => (
              <div key={i} className="flex items-center gap-2 mt-1 text-xs text-amber-700 dark:text-amber-400">
                <Badge variant="outline" className="text-xs h-4">{s.type}</Badge>
                <span className="truncate">{s.description}</span>
              </div>
            ))}
          </div>
        )}

        {/* Email List */}
        <ScrollArea className="flex-1">
          {emails.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-40 text-muted-foreground">
              <Inbox className="h-8 w-8 mb-2" />
              <p className="text-sm">No emails in inbox</p>
              <p className="text-xs">Connect your email to get started</p>
            </div>
          ) : (
            <div className="divide-y">
              {emails.map((email: any) => {
                const cat = categoryConfig[email.category] || categoryConfig.general;
                const pri = priorityConfig[email.priority] || priorityConfig.medium;
                return (
                  <button
                    key={email.id}
                    onClick={() => setSelectedEmailId(email.id)}
                    className={`w-full text-left p-3 hover:bg-muted/50 transition-colors ${
                      selectedEmailId === email.id ? "bg-primary/5 border-l-2 border-l-primary" : ""
                    }`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-1.5">
                          <span className={`${pri.color}`}>{pri.icon}</span>
                          <span className="text-sm font-medium truncate">
                            {email.fromName || email.fromEmail}
                          </span>
                        </div>
                        <p className="text-sm truncate mt-0.5">{email.subject || "(No subject)"}</p>
                        <p className="text-xs text-muted-foreground truncate mt-0.5">
                          {email.bodyText?.substring(0, 80) || ""}
                        </p>
                      </div>
                      <div className="flex flex-col items-end gap-1 shrink-0">
                        <span className="text-xs text-muted-foreground">
                          {email.receivedAt ? new Date(email.receivedAt).toLocaleDateString() : ""}
                        </span>
                        <Badge className={`text-xs ${cat.color}`}>
                          {cat.icon}
                          <span className="ml-1">{cat.label}</span>
                        </Badge>
                      </div>
                    </div>
                  </button>
                );
              })}
            </div>
          )}
        </ScrollArea>
      </div>

      {/* Email Detail / Summary */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {selectedEmail ? (
          <ScrollArea className="flex-1 p-4">
            {/* AI Summary Banner */}
            {summaryResult && (
              <Card className="mb-4 border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-900/10">
                <CardHeader className="py-3 px-4">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Sparkles className="h-4 w-4 text-amber-500" />
                    AI Summary
                  </CardTitle>
                </CardHeader>
                <CardContent className="px-4 pb-3">
                  <p className="text-sm">{summaryResult.summary}</p>
                  {summaryResult.keyTakeaways?.length > 0 && (
                    <div className="mt-2">
                      <p className="text-xs font-medium text-muted-foreground mb-1">Key Takeaways:</p>
                      <ul className="text-xs space-y-0.5">
                        {summaryResult.keyTakeaways.map((t: string, i: number) => (
                          <li key={i} className="flex items-start gap-1">
                            <CheckCircle2 className="h-3 w-3 text-green-500 mt-0.5 shrink-0" />
                            {t}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {summaryResult.actionItems?.length > 0 && (
                    <div className="mt-2">
                      <p className="text-xs font-medium text-muted-foreground mb-1">Action Items:</p>
                      <ul className="text-xs space-y-0.5">
                        {summaryResult.actionItems.map((a: any, i: number) => (
                          <li key={i} className="flex items-start gap-1">
                            <ListTodo className="h-3 w-3 text-blue-500 mt-0.5 shrink-0" />
                            <span>{a.text}</span>
                            {a.assignee && (
                              <Badge variant="outline" className="text-xs h-4 ml-1">{a.assignee}</Badge>
                            )}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </CardContent>
              </Card>
            )}

            {/* Translation Result */}
            {translationResult && (
              <Card className="mb-4 border-blue-200 dark:border-blue-800">
                <CardHeader className="py-3 px-4">
                  <CardTitle className="text-sm flex items-center gap-2">
                    <Languages className="h-4 w-4 text-blue-500" />
                    Translation ({translationResult.sourceLanguage})
                  </CardTitle>
                </CardHeader>
                <CardContent className="px-4 pb-3 text-sm whitespace-pre-wrap">
                  {translationResult.translated}
                </CardContent>
              </Card>
            )}

            {/* Email Header */}
            <div className="mb-4">
              <div className="flex items-start justify-between">
                <div>
                  <h2 className="text-lg font-semibold">{selectedEmail.subject || "(No subject)"}</h2>
                  <p className="text-sm text-muted-foreground">
                    From: <span className="font-medium text-foreground">{selectedEmail.fromName || selectedEmail.fromEmail}</span>
                    {selectedEmail.fromName && (
                      <span className="ml-1 text-xs">&lt;{selectedEmail.fromEmail}&gt;</span>
                    )}
                  </p>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {selectedEmail.receivedAt
                      ? new Date(selectedEmail.receivedAt).toLocaleString()
                      : "Unknown date"}
                  </p>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center gap-1 mt-3 flex-wrap">
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => onSummarize([selectedEmail.id])}
                  disabled={isSummarizing}
                >
                  {isSummarizing ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <Sparkles className="h-3 w-3 mr-1" />}
                  Summarize
                </Button>
                <Button size="sm" variant="outline" onClick={() => onGhostwriteReply(selectedEmail.id)}>
                  <Reply className="h-3 w-3 mr-1" />
                  AI Reply
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => onExtractTodos(selectedEmail.id)}
                  disabled={isExtractingTodos}
                >
                  {isExtractingTodos ? <Loader2 className="h-3 w-3 animate-spin mr-1" /> : <ListTodo className="h-3 w-3 mr-1" />}
                  Extract Todos
                </Button>
                <Button size="sm" variant="outline" onClick={() => onAutoLabel(selectedEmail.id)}>
                  <Tags className="h-3 w-3 mr-1" />
                  Auto-Label
                </Button>
                <Select value={translateLang} onValueChange={setTranslateLang}>
                  <SelectTrigger className="h-8 w-28 text-xs">
                    <Languages className="h-3 w-3 mr-1" />
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="Spanish">Spanish</SelectItem>
                    <SelectItem value="French">French</SelectItem>
                    <SelectItem value="German">German</SelectItem>
                    <SelectItem value="Chinese">Chinese</SelectItem>
                    <SelectItem value="Japanese">Japanese</SelectItem>
                    <SelectItem value="Portuguese">Portuguese</SelectItem>
                    <SelectItem value="Arabic">Arabic</SelectItem>
                  </SelectContent>
                </Select>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => onTranslate(selectedEmail.bodyText || "")}
                >
                  <Globe className="h-3 w-3 mr-1" />
                  Translate
                </Button>
              </div>
            </div>

            <Separator className="my-4" />

            {/* Email Body */}
            <div className="prose prose-sm dark:prose-invert max-w-none">
              {selectedEmail.bodyHtml ? (
                <div dangerouslySetInnerHTML={{ __html: selectedEmail.bodyHtml }} />
              ) : (
                <p className="whitespace-pre-wrap">{selectedEmail.bodyText || "(Empty email body)"}</p>
              )}
            </div>
          </ScrollArea>
        ) : (
          <div className="flex-1 flex items-center justify-center text-muted-foreground">
            <div className="text-center">
              <Mail className="h-12 w-12 mx-auto mb-3 opacity-30" />
              <p className="text-sm">Select an email to read</p>
              <p className="text-xs mt-1">Or use AI Search to find what you need</p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ============================================
// SEARCH PANEL
// ============================================

function SearchPanel({
  searchQuery,
  setSearchQuery,
  searchResult,
  isSearching,
  onSearch,
  onSelectEmail,
}: any) {
  return (
    <div className="flex-1 p-6 overflow-auto">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center gap-2 mb-6">
          <Bot className="h-6 w-6 text-primary" />
          <h2 className="text-xl font-semibold">AI Email Search & Q&A</h2>
        </div>

        <p className="text-sm text-muted-foreground mb-4">
          Ask any question about your emails. Get direct answers, not just links.
        </p>

        <div className="flex gap-2 mb-6">
          <Input
            placeholder="e.g., What was the last price from Acme Corp? / When is the Q2 delivery due?"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && searchQuery && onSearch(searchQuery)}
            className="text-base"
          />
          <Button onClick={() => onSearch(searchQuery)} disabled={!searchQuery || isSearching}>
            {isSearching ? <Loader2 className="h-4 w-4 animate-spin" /> : <Search className="h-4 w-4" />}
          </Button>
        </div>

        {/* Suggested queries */}
        {!searchResult && (
          <div className="space-y-2">
            <p className="text-xs text-muted-foreground font-medium">Try asking:</p>
            {[
              "What invoices are pending payment?",
              "Show me all shipping confirmations from this week",
              "What was the last quote from our freight carriers?",
              "Any emails mentioning production delays?",
            ].map((q) => (
              <button
                key={q}
                onClick={() => {
                  setSearchQuery(q);
                  onSearch(q);
                }}
                className="block text-sm text-primary hover:underline"
              >
                {q}
              </button>
            ))}
          </div>
        )}

        {/* Results */}
        {searchResult && (
          <div className="space-y-4">
            <Card>
              <CardHeader className="py-3">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-amber-500" />
                  AI Answer
                </CardTitle>
              </CardHeader>
              <CardContent className="text-sm whitespace-pre-wrap">
                {searchResult.answer}
              </CardContent>
            </Card>

            {searchResult.relevantEmails?.length > 0 && (
              <div>
                <h3 className="text-sm font-medium mb-2">Relevant Emails</h3>
                <div className="space-y-2">
                  {searchResult.relevantEmails.map((email: any, i: number) => (
                    <Card
                      key={i}
                      className="cursor-pointer hover:border-primary/50 transition-colors"
                      onClick={() => onSelectEmail(email.emailId)}
                    >
                      <CardContent className="p-3">
                        <div className="flex items-start justify-between">
                          <div>
                            <p className="text-sm font-medium">{email.subject}</p>
                            <p className="text-xs text-muted-foreground">
                              From: {email.from} | {email.date}
                            </p>
                            <p className="text-xs mt-1">{email.snippet}</p>
                          </div>
                          <Badge variant="outline" className="text-xs shrink-0">
                            {email.relevanceScore}% match
                          </Badge>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </div>
            )}

            {searchResult.followUpQuestions?.length > 0 && (
              <div>
                <h3 className="text-xs font-medium text-muted-foreground mb-1">Follow-up questions:</h3>
                <div className="flex flex-wrap gap-1">
                  {searchResult.followUpQuestions.map((q: string, i: number) => (
                    <Button
                      key={i}
                      variant="outline"
                      size="sm"
                      className="text-xs"
                      onClick={() => {
                        setSearchQuery(q);
                        onSearch(q);
                      }}
                    >
                      {q}
                    </Button>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ============================================
// COMPOSE / GHOSTWRITER PANEL
// ============================================

function ComposePanel({
  composePrompt,
  setComposePrompt,
  composeRecipient,
  setComposeRecipient,
  composeRecipientName,
  setComposeRecipientName,
  ghostwriteResult,
  isGenerating,
  onGhostwrite,
  writingProfile,
  onLearnStyle,
  isLearning,
}: any) {
  return (
    <div className="flex-1 p-6 overflow-auto">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <Wand2 className="h-6 w-6 text-amber-500" />
            <h2 className="text-xl font-semibold">Ghostwriter</h2>
            <Badge variant="secondary" className="text-xs">
              AI Email Composer
            </Badge>
          </div>
        </div>

        {/* Writing Style Profile Card */}
        <Card className="mb-6">
          <CardHeader className="py-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <BookOpen className="h-4 w-4" />
              Your Writing Style
            </CardTitle>
            <CardDescription className="text-xs">
              Ghostwriter learns your unique writing style from your sent emails
            </CardDescription>
          </CardHeader>
          <CardContent>
            {writingProfile ? (
              <div className="grid grid-cols-2 gap-3 text-xs">
                <div>
                  <span className="text-muted-foreground">Greeting:</span>{" "}
                  <span className="font-medium">{writingProfile.greetingStyle || "Hi"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Closing:</span>{" "}
                  <span className="font-medium">{writingProfile.closingStyle || "Best"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Vocabulary:</span>{" "}
                  <span className="font-medium">{writingProfile.vocabularyLevel || "moderate"}</span>
                </div>
                <div>
                  <span className="text-muted-foreground">Emails sampled:</span>{" "}
                  <span className="font-medium">{writingProfile.emailsSampled || 0}</span>
                </div>
                {writingProfile.toneProfile && (
                  <>
                    <div>
                      <span className="text-muted-foreground">Formality:</span>{" "}
                      <span className="font-medium">{Math.round(((writingProfile.toneProfile as any).formality || 0.5) * 100)}%</span>
                    </div>
                    <div>
                      <span className="text-muted-foreground">Friendliness:</span>{" "}
                      <span className="font-medium">{Math.round(((writingProfile.toneProfile as any).friendliness || 0.5) * 100)}%</span>
                    </div>
                  </>
                )}
              </div>
            ) : (
              <p className="text-xs text-muted-foreground">No writing style learned yet.</p>
            )}
            <Button
              size="sm"
              variant="outline"
              className="mt-3"
              onClick={onLearnStyle}
              disabled={isLearning}
            >
              {isLearning ? (
                <Loader2 className="h-3 w-3 animate-spin mr-1" />
              ) : (
                <Sparkles className="h-3 w-3 mr-1" />
              )}
              {writingProfile ? "Re-learn Style" : "Learn My Style"}
            </Button>
          </CardContent>
        </Card>

        {/* Compose Form */}
        <Card>
          <CardContent className="pt-6 space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label>Recipient Email</Label>
                <Input
                  placeholder="recipient@email.com"
                  value={composeRecipient}
                  onChange={(e) => setComposeRecipient(e.target.value)}
                />
              </div>
              <div>
                <Label>Recipient Name</Label>
                <Input
                  placeholder="Jane Doe"
                  value={composeRecipientName}
                  onChange={(e) => setComposeRecipientName(e.target.value)}
                />
              </div>
            </div>

            <div>
              <Label>What should the email say?</Label>
              <Textarea
                placeholder="Describe what you want to communicate. Be as brief or detailed as you like. Examples:&#10;- 'Follow up on the Q2 pricing discussion'&#10;- 'Thank them for the shipment and ask about the missing items'&#10;- 'Decline the meeting politely, suggest next week instead'"
                value={composePrompt}
                onChange={(e) => setComposePrompt(e.target.value)}
                rows={4}
              />
            </div>

            <Button
              onClick={onGhostwrite}
              disabled={!composePrompt || isGenerating}
              className="w-full"
            >
              {isGenerating ? (
                <Loader2 className="h-4 w-4 animate-spin mr-2" />
              ) : (
                <Wand2 className="h-4 w-4 mr-2" />
              )}
              Generate Email with Ghostwriter
            </Button>
          </CardContent>
        </Card>

        {/* Generated Result */}
        {ghostwriteResult && (
          <Card className="mt-4 border-amber-200 dark:border-amber-800">
            <CardHeader className="py-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-sm flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-amber-500" />
                  Generated Email
                </CardTitle>
                <div className="flex items-center gap-2">
                  <Badge variant="outline" className="text-xs">
                    Tone: {ghostwriteResult.tone}
                  </Badge>
                  <Badge variant="outline" className="text-xs">
                    Style match: {ghostwriteResult.styleMatchScore}%
                  </Badge>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="p-4 bg-background rounded-md border">
                <p className="font-medium text-sm mb-2">Subject: {ghostwriteResult.subject}</p>
                <Separator className="my-2" />
                <p className="text-sm whitespace-pre-wrap">{ghostwriteResult.body}</p>
              </div>

              <div className="flex gap-2 mt-3">
                <Button size="sm">
                  <Send className="h-3 w-3 mr-1" />
                  Send
                </Button>
                <Button size="sm" variant="outline">
                  <Pen className="h-3 w-3 mr-1" />
                  Edit
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={onGhostwrite}
                  disabled={isGenerating}
                >
                  <RefreshCw className="h-3 w-3 mr-1" />
                  Regenerate
                </Button>
              </div>

              {/* Alternative Versions */}
              {ghostwriteResult.alternatives?.length > 0 && (
                <div className="mt-4">
                  <Label className="text-xs text-muted-foreground">Alternative versions:</Label>
                  <div className="space-y-2 mt-1">
                    {ghostwriteResult.alternatives.map((alt: any, i: number) => (
                      <div key={i} className="p-3 bg-muted/50 rounded text-sm">
                        <Badge variant="outline" className="text-xs mb-2">{alt.tone} tone</Badge>
                        <p className="whitespace-pre-wrap">{alt.body}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}

// ============================================
// TODOS PANEL
// ============================================

function TodosPanel({ todos, onUpdateTodo, onCreateTodo }: any) {
  const pendingTodos = todos.filter((t: any) => t.status === "pending" || t.status === "in_progress");
  const doneTodos = todos.filter((t: any) => t.status === "done");

  return (
    <div className="flex-1 p-6 overflow-auto">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <ListTodo className="h-6 w-6 text-primary" />
            <h2 className="text-xl font-semibold">Email Todos</h2>
            <Badge variant="secondary">{pendingTodos.length} active</Badge>
          </div>
        </div>

        <p className="text-sm text-muted-foreground mb-4">
          Action items extracted from your emails. AI identifies tasks, deadlines, and follow-ups automatically.
        </p>

        {/* Active Todos */}
        <div className="space-y-2 mb-6">
          {pendingTodos.length === 0 ? (
            <Card>
              <CardContent className="py-8 text-center text-muted-foreground">
                <CheckCircle2 className="h-8 w-8 mx-auto mb-2 opacity-30" />
                <p className="text-sm">All caught up! No pending email todos.</p>
              </CardContent>
            </Card>
          ) : (
            pendingTodos.map((todo: any) => (
              <Card key={todo.id} className="hover:border-primary/30 transition-colors">
                <CardContent className="py-3 px-4">
                  <div className="flex items-start gap-3">
                    <Checkbox
                      checked={todo.status === "done"}
                      onCheckedChange={() => onUpdateTodo(todo.id, "done")}
                      className="mt-0.5"
                    />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium">{todo.title}</p>
                      {todo.description && (
                        <p className="text-xs text-muted-foreground mt-0.5">{todo.description}</p>
                      )}
                      <div className="flex items-center gap-2 mt-1">
                        {todo.priority && (
                          <Badge variant="outline" className="text-xs">
                            {(priorityConfig[todo.priority] || priorityConfig.medium).icon}
                            <span className="ml-1">{todo.priority}</span>
                          </Badge>
                        )}
                        {todo.dueDate && (
                          <Badge variant="outline" className="text-xs">
                            <Clock className="h-3 w-3 mr-1" />
                            {new Date(todo.dueDate).toLocaleDateString()}
                          </Badge>
                        )}
                        {todo.extractedByAi && (
                          <Badge variant="secondary" className="text-xs">
                            <Sparkles className="h-3 w-3 mr-1" />
                            AI extracted
                          </Badge>
                        )}
                      </div>
                    </div>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => onUpdateTodo(todo.id, "dismissed")}
                    >
                      <X className="h-3 w-3" />
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>

        {/* Completed */}
        {doneTodos.length > 0 && (
          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">
              Completed ({doneTodos.length})
            </h3>
            <div className="space-y-1">
              {doneTodos.slice(0, 10).map((todo: any) => (
                <div key={todo.id} className="flex items-center gap-2 px-2 py-1 text-xs text-muted-foreground">
                  <CheckCircle2 className="h-3 w-3 text-green-500" />
                  <span className="line-through">{todo.title}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ============================================
// BUNDLES & SPLITS PANEL
// ============================================

function BundlesPanel({
  bundles,
  showNewBundleDialog,
  setShowNewBundleDialog,
  newBundleName,
  setNewBundleName,
  newBundleMatchType,
  setNewBundleMatchType,
  onCreateBundle,
  splits,
  showNewSplitDialog,
  setShowNewSplitDialog,
  newSplitName,
  setNewSplitName,
  newSplitFilterType,
  setNewSplitFilterType,
  onCreateSplit,
}: any) {
  return (
    <div className="flex-1 p-6 overflow-auto">
      <div className="max-w-3xl mx-auto space-y-8">
        {/* Bundles Section */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <FolderOpen className="h-6 w-6 text-primary" />
              <h2 className="text-xl font-semibold">Email Bundles</h2>
            </div>
            <Dialog open={showNewBundleDialog} onOpenChange={setShowNewBundleDialog}>
              <DialogTrigger asChild>
                <Button size="sm">
                  <Plus className="h-4 w-4 mr-1" />
                  New Bundle
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Create Email Bundle</DialogTitle>
                  <DialogDescription>
                    Group related emails together for batch processing.
                  </DialogDescription>
                </DialogHeader>
                <div className="space-y-4">
                  <div>
                    <Label>Bundle Name</Label>
                    <Input
                      placeholder="e.g., Vendor Invoices, Shipping Updates"
                      value={newBundleName}
                      onChange={(e) => setNewBundleName(e.target.value)}
                    />
                  </div>
                  <div>
                    <Label>Match Type</Label>
                    <Select value={newBundleMatchType} onValueChange={setNewBundleMatchType}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="sender_domain">By Sender Domain</SelectItem>
                        <SelectItem value="label">By Label</SelectItem>
                        <SelectItem value="subject_pattern">By Subject Pattern</SelectItem>
                        <SelectItem value="ai_category">By AI Category</SelectItem>
                        <SelectItem value="custom">Custom Rules</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <DialogFooter>
                  <Button onClick={onCreateBundle} disabled={!newBundleName}>Create</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>

          <p className="text-sm text-muted-foreground mb-4">
            Bundles group related emails together, like Google Inbox. Process similar emails in batches.
          </p>

          {(bundles as any[]).length === 0 ? (
            <Card>
              <CardContent className="py-8 text-center text-muted-foreground">
                <FolderOpen className="h-8 w-8 mx-auto mb-2 opacity-30" />
                <p className="text-sm">No bundles configured yet.</p>
                <p className="text-xs">Create your first bundle to group related emails.</p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid grid-cols-2 gap-3">
              {(bundles as any[]).map((bundle: any) => (
                <Card key={bundle.id}>
                  <CardContent className="p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <FolderOpen className="h-4 w-4" style={{ color: bundle.color || "#3b82f6" }} />
                      <span className="font-medium text-sm">{bundle.name}</span>
                    </div>
                    {bundle.description && (
                      <p className="text-xs text-muted-foreground">{bundle.description}</p>
                    )}
                    <div className="flex items-center gap-2 mt-2">
                      <Badge variant="outline" className="text-xs">{bundle.matchType}</Badge>
                      {bundle.deliverySchedule !== "instant" && (
                        <Badge variant="secondary" className="text-xs">
                          <Timer className="h-3 w-3 mr-1" />
                          {bundle.deliverySchedule}
                        </Badge>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>

        <Separator />

        {/* Inbox Splits Section */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-2">
              <SlidersHorizontal className="h-6 w-6 text-primary" />
              <h2 className="text-xl font-semibold">Inbox Splits</h2>
            </div>
            <Dialog open={showNewSplitDialog} onOpenChange={setShowNewSplitDialog}>
              <DialogTrigger asChild>
                <Button size="sm">
                  <Plus className="h-4 w-4 mr-1" />
                  New Split
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Create Inbox Split</DialogTitle>
                  <DialogDescription>
                    Divide your inbox into focused tabs so you can stay responsive where it matters most.
                  </DialogDescription>
                </DialogHeader>
                <div className="space-y-4">
                  <div>
                    <Label>Split Name</Label>
                    <Input
                      placeholder="e.g., VIP, Team, Updates"
                      value={newSplitName}
                      onChange={(e) => setNewSplitName(e.target.value)}
                    />
                  </div>
                  <div>
                    <Label>Filter Type</Label>
                    <Select value={newSplitFilterType} onValueChange={setNewSplitFilterType}>
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="important">Important</SelectItem>
                        <SelectItem value="team">Team</SelectItem>
                        <SelectItem value="notifications">Notifications</SelectItem>
                        <SelectItem value="newsletters">Newsletters</SelectItem>
                        <SelectItem value="custom">Custom</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <DialogFooter>
                  <Button onClick={onCreateSplit} disabled={!newSplitName}>Create</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>

          <p className="text-sm text-muted-foreground mb-4">
            Splits divide your inbox into focused tabs. Stay responsive where it matters most.
          </p>

          {(splits as any[]).length === 0 ? (
            <Card>
              <CardContent className="py-8 text-center text-muted-foreground">
                <SlidersHorizontal className="h-8 w-8 mx-auto mb-2 opacity-30" />
                <p className="text-sm">No inbox splits configured yet.</p>
              </CardContent>
            </Card>
          ) : (
            <div className="grid grid-cols-3 gap-3">
              {(splits as any[]).map((split: any) => (
                <Card key={split.id}>
                  <CardContent className="p-4 text-center">
                    <span className="font-medium text-sm">{split.name}</span>
                    <Badge variant="outline" className="text-xs mt-2 block mx-auto w-fit">
                      {split.filterType}
                    </Badge>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ============================================
// SETTINGS PANEL
// ============================================

function SettingsPanel({ writingProfile, onLearnStyle, isLearning }: any) {
  return (
    <div className="flex-1 p-6 overflow-auto">
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="flex items-center gap-2 mb-6">
          <SlidersHorizontal className="h-6 w-6 text-primary" />
          <h2 className="text-xl font-semibold">Email AI Settings</h2>
        </div>

        {/* Ghostwriter Settings */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <Wand2 className="h-5 w-5 text-amber-500" />
              Ghostwriter Profile
            </CardTitle>
            <CardDescription>
              Your AI writing assistant learns from your sent emails to match your personal style.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {writingProfile ? (
              <>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1">
                    <Label className="text-xs text-muted-foreground">Greeting Style</Label>
                    <p className="text-sm font-medium">{writingProfile.greetingStyle || "Not set"}</p>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-muted-foreground">Closing Style</Label>
                    <p className="text-sm font-medium">{writingProfile.closingStyle || "Not set"}</p>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-muted-foreground">Vocabulary Level</Label>
                    <p className="text-sm font-medium capitalize">{writingProfile.vocabularyLevel || "Moderate"}</p>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-muted-foreground">Uses Emoji</Label>
                    <p className="text-sm font-medium">{writingProfile.useEmoji ? "Yes" : "No"}</p>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-muted-foreground">Emails Analyzed</Label>
                    <p className="text-sm font-medium">{writingProfile.emailsSampled || 0}</p>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-muted-foreground">Last Trained</Label>
                    <p className="text-sm font-medium">
                      {writingProfile.lastTrainedAt
                        ? new Date(writingProfile.lastTrainedAt).toLocaleDateString()
                        : "Never"}
                    </p>
                  </div>
                </div>

                {writingProfile.toneProfile && (
                  <div>
                    <Label className="text-xs text-muted-foreground">Tone Profile</Label>
                    <div className="grid grid-cols-4 gap-2 mt-1">
                      {Object.entries(writingProfile.toneProfile as Record<string, number>).map(([key, value]) => (
                        <div key={key} className="text-center">
                          <div className="h-2 bg-muted rounded-full overflow-hidden">
                            <div
                              className="h-full bg-primary rounded-full"
                              style={{ width: `${(value as number) * 100}%` }}
                            />
                          </div>
                          <span className="text-xs text-muted-foreground capitalize mt-0.5 block">{key}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                {writingProfile.commonPhrases && (writingProfile.commonPhrases as string[]).length > 0 && (
                  <div>
                    <Label className="text-xs text-muted-foreground">Common Phrases</Label>
                    <div className="flex flex-wrap gap-1 mt-1">
                      {(writingProfile.commonPhrases as string[]).map((phrase: string, i: number) => (
                        <Badge key={i} variant="secondary" className="text-xs">
                          {phrase}
                        </Badge>
                      ))}
                    </div>
                  </div>
                )}
              </>
            ) : (
              <p className="text-sm text-muted-foreground">
                No writing profile yet. Click below to analyze your sent emails and create one.
              </p>
            )}

            <Button onClick={onLearnStyle} disabled={isLearning}>
              {isLearning ? (
                <Loader2 className="h-4 w-4 animate-spin mr-2" />
              ) : (
                <Sparkles className="h-4 w-4 mr-2" />
              )}
              {writingProfile ? "Re-analyze Writing Style" : "Learn My Writing Style"}
            </Button>
          </CardContent>
        </Card>

        {/* AI Features */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <Bot className="h-5 w-5" />
              AI Features
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium">Instant Thread Summaries</p>
                <p className="text-xs text-muted-foreground">Show AI summaries at the top of email threads</p>
              </div>
              <Switch defaultChecked />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium">Auto-Label Emails</p>
                <p className="text-xs text-muted-foreground">Automatically categorize incoming emails with smart labels</p>
              </div>
              <Switch defaultChecked />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium">Extract Action Items</p>
                <p className="text-xs text-muted-foreground">Automatically detect todos and deadlines in emails</p>
              </div>
              <Switch defaultChecked />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium">Smart Unsubscribe</p>
                <p className="text-xs text-muted-foreground">One-click block and unsubscribe from unwanted emails</p>
              </div>
              <Switch />
            </div>
            <Separator />
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium">Auto-Translation</p>
                <p className="text-xs text-muted-foreground">Automatically translate incoming emails in foreign languages</p>
              </div>
              <Switch />
            </div>
          </CardContent>
        </Card>

        {/* Delivery Schedule */}
        <Card>
          <CardHeader>
            <CardTitle className="text-base flex items-center gap-2">
              <Timer className="h-5 w-5" />
              Delivery Schedule
            </CardTitle>
            <CardDescription>
              Avoid interruptions by deferring when emails arrive in your inbox.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium">Batch Delivery</p>
                  <p className="text-xs text-muted-foreground">Receive emails at scheduled intervals instead of instantly</p>
                </div>
                <Switch />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <Label className="text-xs">Morning batch</Label>
                  <Input type="time" defaultValue="09:00" className="text-sm" />
                </div>
                <div>
                  <Label className="text-xs">Afternoon batch</Label>
                  <Input type="time" defaultValue="14:00" className="text-sm" />
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Checkbox defaultChecked />
                <Label className="text-xs">Always deliver urgent emails immediately</Label>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
