#!/usr/bin/env bash
#
# Cloud Agent install script for the AI ERP System.
#
# Idempotent, non-interactive setup that prepares a fresh Cloud Agent VM to run
# the app end-to-end:
#   1. Ensure a local MySQL 8 server is installed and running.
#   2. Ensure the ai_erp_system database + app user exist.
#   3. Install node dependencies (pnpm).
#   4. Create a dev .env if one is not already present.
#   5. Apply the full schema from drizzle/schema.ts (see scripts/cloud-db-setup.mjs).
#
# Safe to run repeatedly.
set -euo pipefail

cd "$(dirname "$0")/.."

DB_NAME="ai_erp_system"
DB_USER="erp_user"
DB_PASS="erp_password"
export DATABASE_URL="mysql://${DB_USER}:${DB_PASS}@127.0.0.1:3306/${DB_NAME}"

echo "[install] Ensuring MySQL server is installed..."
if ! command -v mysqld >/dev/null 2>&1 && ! command -v mariadbd >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  sudo apt-get update -y
  sudo apt-get install -y mysql-server mysql-client
fi

echo "[install] Starting MySQL server..."
sudo service mysql start 2>/dev/null || sudo mysqld_safe --datadir=/var/lib/mysql >/dev/null 2>&1 &
# Wait for the server to accept connections.
for i in $(seq 1 30); do
  if sudo mysqladmin ping >/dev/null 2>&1; then break; fi
  sleep 1
done
sudo mysqladmin ping

echo "[install] Ensuring database and application user exist..."
sudo mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED WITH mysql_native_password BY '${DB_PASS}';
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED WITH mysql_native_password BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL

echo "[install] Installing node dependencies..."
corepack enable pnpm 2>/dev/null || true
pnpm install --frozen-lockfile

if [ ! -f .env ]; then
  echo "[install] Writing dev .env..."
  cat > .env <<ENV
# Local development environment (Cloud Agent) — generated by cloud-agent-install.sh
NODE_ENV=development
PORT=3000

APP_URL=http://localhost:3000
VITE_APP_URL=http://localhost:3000
PUBLIC_APP_URL=http://localhost:3000

VITE_APP_ID=ai_erp_system
VITE_APP_TITLE=AI ERP System

DATABASE_URL=${DATABASE_URL}

# Dev-only JWT secret (>= 32 chars). Not for production use.
JWT_SECRET=dev-local-jwt-secret-please-change-0123456789abcdef

LLM_PROVIDER=anthropic
LLM_MODEL=claude-sonnet-4-20250514
ENV
else
  echo "[install] .env already exists — leaving it untouched."
fi

echo "[install] Applying database schema (idempotent)..."
node scripts/cloud-db-setup.mjs

# Cleanly stop MySQL so the datadir baked into the environment build snapshot is
# consistent. The per-boot start script brings it back up (see cloud-agent-start.sh).
echo "[install] Stopping MySQL for a clean snapshot..."
sudo service mysql stop >/dev/null 2>&1 || true

echo "[install] Done."
